Repository MockBukkit/MockBukkit, pull requests merged in 2022-12, with the labels that each got.

#697 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CodMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CreatureMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SalmonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SchoolableFishMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TropicalFishMock.java
Labels: release/patch

#681 Add Guardian Entites
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ElderGuardianMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GuardianMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MobMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ElderGuardianMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GuardianMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MobMockTest.java
Labels: Hacktoberfest, release/minor

#699 Implement FrictionState
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ItemEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/minor

#675 Implement OfflinePlayerMock#isOp and OfflinePlayerMock#setOp
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockPlayerListTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: Hacktoberfest, release/minor

#698 Implement ConsoleCommandSenderMock's Spigot object
  src/main/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
Labels: release/minor

#700 Implement Fireballs
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DragonFireballMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FireballMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LargeFireballMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SizedFireballMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SmallFireballMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WitherSkullMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DragonFireballMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FireballMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LargeFireballMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SizedFireballMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SmallFireballMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WitherSkullMockTest.java
Labels: release/minor

#705 Fix Errors in Documentation and fix formatting
  docs/conf.py
  docs/custom_server_mock.rst
  docs/entity_mock.rst
  docs/first_tests.rst
  docs/getting_started.rst
  docs/message_target.rst
  docs/player_mock.rst
  docs/scheduler_mock.rst
  docs/world_mock.rst
Labels: release/none

#706 Fix Highlighting Error
  docs/getting_started.rst
Labels: release/none

#707 Fix Docs
  docs/getting_started.rst
Labels: release/none

#685 Update README examples
  README.md
Labels: release/none

#708 Remove hamcrest as a dependency
  build.gradle
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/none

#712 Add methods to the SignStateMock
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SignMockTest.java
Labels: release/minor

#713 Add a SwitchMock BlockData, (buttons, and levers)
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataKey.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/SwitchMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/SwitchMockTest.java
Labels: release/minor

#704 Update to 1.19.3
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#714 OfflinePlayerMock: fix incorrect return type
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
Labels: release/patch

#563 Fix code Style
  .editorconfig
  .github/pull_request_template.md
  README.md
  build.gradle
  docs/index.rst
  extra/TestPlugin/build.gradle
  extra/TestPlugin/src/main/java/be/seeseemelk/testplugin/TestPlugin.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataKey.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/SwitchMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/AnvilInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/CartographyInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/EnchantingInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/GrindstoneInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/LecternInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/LlamaInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/LoomInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/SimpleInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/SmithingInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/StonecutterInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BundleMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CompassMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CrossbowMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/EnchantedBookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkEffectMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/KnowledgeBookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/LeatherArmorMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/MapMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/TropicalFishBucketMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/tags/TagWrapperMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/SwitchMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PolarBearMockTest.java
Labels: release/none

#715 Remove SimpleInventoryMock
  src/main/java/be/seeseemelk/mockbukkit/inventory/SimpleInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/PlayerInventoryViewTest.java
Labels: enhancement, release/none

#719 Remove all of our own deprecated classes/methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/ThreadAccessException.java
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: 3.0

#716 Stub new Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TadpoleMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/patch

#722 Move Entity Spawn Tests to Parameterized Test
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/none

#677 Add a MockBukkitExtension for use with JUnit
  src/main/java/be/seeseemelk/mockbukkit/MockBukkitExtension.java
  src/main/java/be/seeseemelk/mockbukkit/MockBukkitInject.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SkullMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitExtensionTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/StairsMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/TrapDoorMockTest.java
Labels: Hacktoberfest, release/minor
