Repository MockBukkit/MockBukkit, pull requests merged in 2022-11, with the labels that each got.

#683 Remove JacksonChen666's treecapitator in README examples section
  README.md
Labels: good first issue, Hacktoberfest, release/none

#684 Implement Polar bear mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PolarBearMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PolarBearMockTest.java
Labels: release/minor

#686 Fix #hasPlayedBefore not behaving as it should
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockPlayerListTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#687 Fix Polar Bears not being spawnable
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
Labels: release/patch

#690 Fix typo in AbstractSkeletonMock#assertAggressiveAttack
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMock.java
Labels: release/patch

#692 Implement methods for PlayerMock
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor
