Repository MockBukkit/MockBukkit, pull requests merged in 2022-07, with the labels that each got.

#518 Create a more robust .gitignore
  .gitignore
Labels: release/none

#521 Fix inconsistent BlockState constructor visibility
  src/main/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CommandBlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ComparatorMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ConduitMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CreatureSpawnerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DaylightDetectorMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EnchantingTableMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/JigsawMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/JukeboxMock.java
Labels: release/patch

#494 Implement the SculkCatalyst BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SculkCatalystMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SculkCatalystMockTest.java
Labels: release/minor

#525 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
Labels: release/patch

#523 Add Anvil Inventory
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/AnvilInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/AnvilInventoryMockTest.java
Labels: release/minor

#526 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#493 Implement the End Gateway BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EndGatewayMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/EndGatewayMockTest.java
Labels: release/minor

#498 Implement the PluginManagerMock default permission methods
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/minor

#527 Add AxolotlMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AxolotlMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AxolotlMockTest.java
Labels: release/minor

#528 Add Simple Mobs
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BlazeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CaveSpiderMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GiantMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SpiderMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BlazeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CaveSpiderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GiantMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SpiderMockTest.java
Labels: release/minor

#524 Add Skeleton Entities
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/StrayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WitherSkeletonMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SkeletonMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/StrayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WitherSkeletonMockTest.java
Labels: release/minor

#529 Add Simple Animal Mocks
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CowMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ChickenMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CowMockTest.java
Labels: release/minor

#530 Fix exceptions from event handlers not failing tests
  src/main/java/be/seeseemelk/mockbukkit/exception/EventHandlerException.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/patch

#534 Fix scheduler still hanging under certain circumstances
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/patch

#517 Implement the Structure BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/StructureMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/StructureMockTest.java
Labels: release/minor

#511 Implement the Skull BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SkullMock.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SkullMockTest.java
Labels: release/minor

#533 Implements the Animals#isBreedingItem Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/AnimalsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AxolotlMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AnimalsMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AxolotlMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ChickenMockTest.java
Labels: release/minor

#539 Add issue templates for bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: release/none

#540 Stub new Methods
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
Labels: release/none

#522 Fix #assertSaid working with strings instead of components
  src/main/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/MessageTarget.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: release/patch

#537 Backport #534 and part of #474 to 1.18
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: Older branch, release/patch

#545 Create CODEOWNERS
  .github/CODEOWNERS
Labels: release/none

#549 Add BeaconInventoryMock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMockTest.java
Labels: release/minor

#546 Fix ServerMock#getBukkitVersion not returning the full version
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/UnsafeValuesTest.java
Labels: release/patch

#553 Bring old InventoryMocks in Line with new ones
  src/main/java/be/seeseemelk/mockbukkit/inventory/GrindstoneInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/LecternInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/LecternInventoryMockTest.java
Labels: release/patch

#555 Add Enchanting Inventory
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/EnchantingInventoryMock.java
Labels: release/minor

#556 Update PlayerProfileMock#update return type
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
Labels: release/patch

#552 Implement CartographyInventoryMock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/CartographyInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/CartographyInventoryMockTest.java
Labels: release/minor

#489 Remove .astylerc
  .astylerc
Labels: release/none

#497 implement ConsoleCommandSenderMock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/CommandResultTest.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
Labels: release/minor

#542 Add Missed Tests
  src/test/java/be/seeseemelk/mockbukkit/entity/AgeableMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AnimalsMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ChestedHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/none

#558 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#551 Fix Online Player Handeling
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#560 Re-enable testDisconnectWithPlayerOffline
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/none

#557 Project cleanup
  src/main/java/be/seeseemelk/mockbukkit/MockChunkData.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SculkCatalystMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SkullMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/MessageTarget.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AgeableMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AnimalsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AxolotlMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DonkeyMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermanMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MuleMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SkeletonHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/StrayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WitherSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/exception/EventHandlerException.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/AnvilInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/EnchantingInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/ListenerEntry.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTask.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkSnapshotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/EndGatewayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/boss/KeyedBossBarMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/generator/BiomeProviderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/AnvilInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BrewerInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/CartographyInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/LecternInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/TropicalFishBucketMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/map/MapCanvasMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
Labels: release/patch

#541 Implement Ban, Kick and Whitelist
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#562 Implement PlayerProfileMock#serialize
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/test/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMockTest.java
Labels: release/minor

#561 Prepare for future BlockData implementations
  src/main/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BedMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BedMockTest.java
Labels: release/patch

#564 Add Loom Inventory Mock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/LoomInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/LoomInventoryMockTest.java
Labels: release/minor

#565 Add Stonecutter Inventory Mock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/StonecutterInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/StonecutterInventoryTest.java
Labels: release/minor

#566 Fix non-standard output of Bukkit#getVersion
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#568 Implement Killer
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/minor

#567 Implement Jumping
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/minor

#569 Implement Invisibility
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/minor

#570 Implement Smithing Inventory
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/SmithingInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/SmithingInventoryMockTest.java
Labels: release/minor

#572 Implement ServerMock#getBannedPlayers
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#548 Add Simulate Consume Item
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#571 Implement WorkbenchInventoryMock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/WorkbenchInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/WorkbenchInventoryMockTest.java
Labels: release/minor

#579 Implement InventoryMock#close()
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
Labels: release/minor

#580 Add CatMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CatMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CatMockTest.java
Labels: release/minor

#576 Add an implementation for the passenger API
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MinecartMockTest.java
Labels: release/minor

#583 Add Frog Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FrogMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FrogMockTest.java
Labels: release/minor

#584 Add Fox Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FoxMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FoxMockTest.java
Labels: release/minor

#586 Provide component serializers with service providers
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/adventure/LegacyComponentSerializerProviderImpl.java
  src/main/resources/META-INF/services/net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer$Provider
  src/test/java/be/seeseemelk/mockbukkit/adventure/LegacyComponentSerializerTest.java
Labels: release/patch

#585 Implement Fish Mocks
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CodMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FishMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PufferFishMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SalmonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TadpoleMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TropicalFishMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CodMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FishMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PufferFishMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SalmonMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TadpoleMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TropicalFishMockTest.java
Labels: release/minor

#587 Add Mushroom Cow Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MushroomCowMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MushroomCowMockTest.java
Labels: release/minor

#588 Add Ghast Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FlyingMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GhastMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GhastMockTest.java
Labels: release/minor
