Repository MockBukkit/MockBukkit, pull requests merged in 2022-06, with the labels that each got.

#402 Update the usage section of the README.md
  README.md
Labels: release/none

#328 Cleanup and add new entitiy implementations to prepare for new entities
  build.gradle
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AgeableMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AmbientMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AnimalsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChestedHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CreatureMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ExperienceOrbMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FireworkMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HangingMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MobMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MockRangedEntity.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MonsterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMockFactory.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SimpleEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SimpleMobMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SimpleMonsterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TameableAnimalMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/VehicleMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieMock.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ItemEntityMockTest.java
Labels: release/minor

#410 Disable renovate dashboard
  .github/renovate.json
Labels: release/none

#409 Add more BlockDataMock functionality
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataTest.java
Labels: release/minor

#406 Add test to make sure config.yml is parsed
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
  src/test/resources/config.yml
Labels: release/none

#426 Added ServerMock#getCommandTabComplete
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/TestPlugin.java
Labels: release/minor

#429 Changes to GetTabComplete
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/TestPlugin.java
Labels: release/patch

#356 Implement PlayerMock#getAddress
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#319 Implement some of the PlayerMock#send... methods
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#403 Fix BlockStateMock#update(true) not updating block type
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BlockStateMockTest.java
Labels: release/patch

#290 Fixed Issues with Simulate BlockPlaceEvent
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#368 Implement CompassMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CompassMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/CompassMetaMockTest.java
Labels: release/minor

#297 feat(scheduler): add `waitAsyncEventsFinished()` to wait for async event execution
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/minor

#437 Implement Bell BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BellMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BellMockTest.java
Labels: release/minor

#335 Automatically keep ServerMock#getBukkitVersion up to date
  build.gradle
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
Labels: release/minor

#434 Make all constructors in all abstract classes protected
  src/main/java/be/seeseemelk/mockbukkit/block/state/ContainerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/TileStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CreatureMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MobMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MonsterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMock.java
Labels: release/patch

#440 Fix some test code smells
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/metadata/MetadataTableTest.java
Labels: release/none

#420 Decrease chance of BukkitSchedulerMockTest randomly failing
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/none

#443 Implement Campfire BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CampfireMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/CampfireMockTest.java
Labels: release/minor

#421 Implement Banner BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BannerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BannerMockTest.java
Labels: release/minor

#430 Implement AmethystCluster BlockData
  src/main/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMockTest.java
Labels: release/minor

#418 Fix BlockStateMock copy constructors not cloning all values
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ContainerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EnderChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
  src/main/java/be/seeseemelk/mockbukkit/metadata/MetadataTable.java
Labels: release/patch

#433 Don't implement Cloneable in BlockStateMock
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
Labels: release/patch

#427 Fix the README bugs badge link
  README.md
Labels: release/none

#441 Fix ContainerMock not overriding #customName
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ContainerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DropperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/HopperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
Labels: release/patch

#436 Fix PlayerMock#setGameMode not calling the PlayerGameModeChangeEvent
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#432 Create and use MockBukkit#ensureMocking
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
Labels: release/patch

#425 Add Automatic-Module-Name manifest attribute
  build.gradle
Labels: release/patch

#446 Don't override ContainerMock#customName
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DropperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/HopperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
Labels: release/patch

#358 Fix AsyncPlayerPreLoginEvent not being called when adding a player to the server
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#414 Fix serialized ItemMeta keys
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
Labels: release/patch

#452 Implement an abstract MinecartMock
  src/main/java/be/seeseemelk/mockbukkit/entity/MinecartMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MinecartMockTest.java
Labels: release/minor

#439 Add an AbstractFurnaceMock
  src/main/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMockTest.java
Labels: release/minor

#354 Finish implementing attributes (mostly)
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributesMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/test/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
Labels: release/minor

#342 Add implementation for InventoryMock: getMaxStackSize and setMaxStackSize
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
Labels: release/minor

#447 Implement CommandBlock BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CommandBlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/CommandBlockHolderMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/CommandBlockMockTest.java
Labels: release/minor

#455 Update v1.19
  build.gradle
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributesMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CommandBlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DropperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/HopperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/CommandBlockHolderMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/CommandBlockMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
Labels: release/none

#445 Update Mockbukkit to 1.19
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/boss/BossBarMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FireworkMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HangingMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/sound/AudioExperience.java
  src/main/java/be/seeseemelk/mockbukkit/sound/SoundReceiver.java
  src/main/java/be/seeseemelk/mockbukkit/statistic/StatisticsMock.java
  src/main/java/be/seeseemelk/mockbukkit/tags/TagParser.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SignMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/boss/BossBarMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/boss/KeyedBossBarMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FireworkMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/tags/TagParserTest.java
Labels: release/minor

#415 Implement PlayerMock's player list header/footer methods
  build.gradle
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/minor

#365 Implement maps
  .gitattributes
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/MapMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/map/MapCanvasMock.java
  src/main/java/be/seeseemelk/mockbukkit/map/MapRendererMock.java
  src/main/java/be/seeseemelk/mockbukkit/map/MapViewMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/MapMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/map/MapCanvasMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/map/MapViewMockTest.java
  src/test/resources/map/img.ser
  src/test/resources/map/img_text.ser
Labels: release/minor

#457 Update README.md
  README.md
Labels: release/none

#460 Fix readme
  .github/workflows/gradle.yml
  README.md
Labels: release/none

#330 Implement the rest of the WorldMock#getEntities methods
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#331 Implement biomes
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/ChunkSnapshotMock.java
  src/main/java/be/seeseemelk/mockbukkit/MockChunkData.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/BiomeProviderMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkSnapshotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/MockChunkDataTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/generator/BiomeProviderMockTest.java
Labels: release/minor

#379 Implement weather
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#367 Implement BundleMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BundleMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/BundleMetaMockTest.java
Labels: release/minor

#327 Add FishHookMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FishHookMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ProjectileMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FishHookMockTest.java
Labels: release/minor

#451 Implement the DaylightDetector BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DaylightDetectorMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/DaylightDetectorMockTest.java
Labels: release/minor

#412 Implement all of Paper's Component methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/PlayerMessagingTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
Labels: release/minor

#419 Implement BlockStateMock #equals and #hashCode
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BannerMockTest.java
Labels: release/minor

#222 Implement WorldBorderMock and WorldMock#getWorldBorder
  src/main/java/be/seeseemelk/mockbukkit/WorldBorderMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldBorderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#450 Implement the CreatureSpawner BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CreatureSpawnerMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/CreatureSpawnerMockTest.java
Labels: release/minor

#454 Add Allay Mock
  src/main/java/be/seeseemelk/mockbukkit/entity/AllayMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockPlayerListTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AllayMockTest.java
Labels: release/minor

#469 Implement new methods
  src/main/java/be/seeseemelk/mockbukkit/block/state/BannerMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BannerMockTest.java
Labels: release/minor

#466 Fixes ChunkMock#getChunkSnapshot passing in oversized maps to ChunkSnapshotMock
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
Labels: release/patch

#471 Prevent having objectives or teams with the same name
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/TeamMockTest.java
Labels: release/patch

#468 Create a Jukebox BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/JukeboxMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/JukeboxMockTest.java
Labels: release/minor

#475 Add Spawn Flags in WorldMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#476 Add Spawn Test for AllayMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AllayMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/patch

#370 Implement AxolotlBucketMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/AxolotlBucketMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/AxolotlBucketMetaMockTest.java
Labels: release/minor

#465 Add SheepMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SheepMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SheepMockTest.java
Labels: release/minor

#474 Fix smelly code
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SuspiciousStewMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/ListenerEntry.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/RepeatingTask.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTask.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/main/java/be/seeseemelk/mockbukkit/statistic/StatisticsMock.java
  src/main/java/org/bukkit/plugin/java/PluginClassLoaderUtils.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AllayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/ScoreMockTest.java
Labels: release/patch

#467 Create a Jigsaw BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/JigsawMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/JigsawMockTest.java
Labels: release/minor

#477 Add Enderman Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermanMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EndermanMockTest.java
Labels: release/minor

#416 Implement Bed BlockData
  src/main/java/be/seeseemelk/mockbukkit/block/data/BedMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BedMockTest.java
Labels: release/minor

#478 Add InventoryMock#getViewers() and related Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
Labels: release/minor

#481 Optimize logo
  logo.png
Labels: release/none

#483 Stub new Methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
Labels: release/patch

#463 Add an EnchantingTable BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EnchantingTableMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/EnchantingTableMockTest.java
Labels: release/minor

#449 Implement the Conduit BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ConduitMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/ConduitMockTest.java
Labels: release/minor

#482 Update README.md
  README.md
Labels: release/none

#438 Implement BlastFurnace BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlastFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BlastFurnaceMockTest.java
Labels: release/minor

#484 Remove unused JOIN_MESSAGE variable
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
Labels: release/patch

#442 Implement BrewingStand BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMockTest.java
Labels: release/minor

#485 Add the wool_carpets tag data
  src/main/resources/tags/blocks/_list.json
  src/main/resources/tags/blocks/wool_carpets.json
Labels: release/minor

#464 Cleanup existing Block State implementations to be in line with new ones
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DropperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EnderChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/HopperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BarrelMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BellMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/ChestMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/DispenserMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/DropperMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/EnderChestMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/HopperMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/LecternMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SignMockTest.java
Labels: release/patch

#422 Implement Beacon BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BeaconMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BeaconMockTest.java
Labels: release/minor

#473 Enforce nullability (pt.1)
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributesMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BannerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CampfireMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ContainerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CreatureSpawnerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/boss/BossBarMock.java
  src/main/java/be/seeseemelk/mockbukkit/boss/KeyedBossBarMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/CommandResult.java
  src/main/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/MessageTarget.java
  src/main/java/be/seeseemelk/mockbukkit/command/MockCommandMap.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AllayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AmbientMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AnimalsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CreatureMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FishHookMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MobMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MockRangedEntity.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MonsterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMockFactory.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SimpleEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SimpleMonsterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TameableAnimalMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/BiomeProviderMock.java
  src/main/java/be/seeseemelk/mockbukkit/help/HelpMapMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/CommandResultTest.java
Labels: release/patch

#417 Implement Bed BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BedMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BedMockTest.java
Labels: release/minor

#373 Implement SpawnEggMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SpawnEggMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/SpawnEggMetaMockTest.java
Labels: release/minor

#491 Implement synchronous BukkitSchedulerMock runTask methods with consumers
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/RepeatingTask.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTask.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/RepeatingTaskTest.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTaskTest.java
Labels: release/minor

#500 Implement Warden Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WardenMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WardenMockTest.java
Labels: release/minor

#501 Implement Brewer Inventory
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/BrewerInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BrewerInventoryMockTest.java
Labels: release/minor

#503 Horse mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/HorseInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/HorseInventoryMockTest.java
Labels: release/minor

#505 Code style 2
  src/main/java/be/seeseemelk/mockbukkit/Coordinate.java
  src/main/java/be/seeseemelk/mockbukkit/MockBanList.java
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/command/MessageTarget.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AnimalsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/HorseInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/EnchantedBookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkEffectMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/KnowledgeBookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/LeatherArmorMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/ListenerEntry.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/RepeatingTask.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTask.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
  src/main/java/be/seeseemelk/mockbukkit/tags/TagParser.java
  src/test/java/be/seeseemelk/mockbukkit/SecondTestPlugin.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/TestPlugin.java
  src/test/java/be/seeseemelk/mockbukkit/WorldBorderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EndermanMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BrewerInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/HorseInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/EnchantmentMock.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
  src/test/java/be/seeseemelk/mockbukkit/tags/RegistryTest.java
Labels: release/patch

#506 Implement BukkitSchedulerMock#getMainThreadExecutor
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/minor

#495 Implement a better system for type checking BlockStateMocks
  src/main/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BannerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BeaconMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BedMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BeehiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BellMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlastFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CampfireMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CommandBlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ComparatorMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ConduitMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CreatureSpawnerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DaylightDetectorMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserProjectileSourceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/DropperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EnchantingTableMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/EnderChestMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/HopperMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/JigsawMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/JukeboxMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/LecternMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ShulkerBoxMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BedMockTest.java
Labels: release/patch

#492 Move Methods from PlayerMock to HumanEntityMock
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermanMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HumanEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#507 Implement other HorseMock methods
  src/main/java/be/seeseemelk/mockbukkit/entity/HorseMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HorseMockTest.java
Labels: release/minor

#508 Implement the remaining methods of Team
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/TeamMockTest.java
Labels: release/minor

#514 Add RickRoleMock
  src/main/java/be/seeseemelk/mockbukkit/RickRollMock.java
  src/test/java/be/seeseemelk/mockbukkit/RickRollMockTest.java
Labels: release/minor

#502 Add FurnaceInventoryMock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlastFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BlastFurnaceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMockTest.java
Labels: release/minor

#510 Implement the SculkShrieker BlockState
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SculkShriekerMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SculkShriekerMockTest.java
Labels: release/minor

#513 Add More Horse Mocks
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DonkeyMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MuleMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SkeletonHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/AbstractHorseInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/HorseInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/LlamaInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/AbstractFurnaceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BlastFurnaceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DonkeyMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LlamaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MuleMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SkeletonHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ZombieHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/FurnaceInventoryMockTest.java
Labels: release/minor

#516 Revert "Add RickRoleMock"
  src/main/java/be/seeseemelk/mockbukkit/RickRollMock.java
  src/test/java/be/seeseemelk/mockbukkit/RickRollMockTest.java
Labels: release/none

#515 Add some more Tests Pt 1
  src/test/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BannerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BarrelMockTest.java
Labels: release/none
