Repository MockBukkit/MockBukkit, pull requests merged in 2022-08, with the labels that each got.

#591 Fix some methods throwing UnsupportedOperationExceptions instead of UnimplementedOperationExceptions
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FishHookMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/MapMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/map/MapRendererMock.java
  src/main/java/be/seeseemelk/mockbukkit/map/MapViewMock.java
Labels: release/patch

#590 Bump Paper to 1.19.1
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/minor

#597 Implement ServerMock#permissionMessage and getPermissionMessage
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#598 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
Labels: release/patch

#600 Stub new Methods
  src/main/java/be/seeseemelk/mockbukkit/WorldBorderMock.java
Labels: release/patch

#589 Fix ZombieMock not failing on villager operations
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieMock.java
Labels: release/patch

#601 Bump Paper to 1.19.2
  settings.gradle
Labels: release/patch

#594 Fix publishing to maven local not working
  build.gradle
Labels: release/none

#603 Fix domestication
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMockTest.java
Labels: release/patch

#593 Properly link external Javadocs
  build.gradle
Labels: release/none

#604 Add missed Tests
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AgeableMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AllayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AmbientMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArmorStandMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FishHookMockTest.java
Labels: release/patch

#606 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AllayMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
Labels: release/patch

#605 Add Bee Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BeeMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BeeMockTest.java
Labels: release/minor

#607 Add Wolf Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WolfMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WolfMockTest.java
Labels: release/minor

#608 Add Creeper Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CreeperMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CreeperMockTest.java
Labels: release/minor

#611 Add Pig Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PigMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PigMockTest.java
Labels: release/minor

#610 Add Egg Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EggMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ThrowableProjectileMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EggMockTest.java
Labels: release/minor

#613 Stub new Methods
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WardenMock.java
Labels: release/patch

#609 Add Goat Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GoatMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GoatMockTest.java
Labels: release/minor

#615 Remove getKiller and setKiller method stubs
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch
