Repository MockBukkit/MockBukkit, pull requests merged in 2022-09, with the labels that each got.

#621 Fix main hand slot and nullability issues
  src/main/java/be/seeseemelk/mockbukkit/adventure/LegacyComponentSerializerProviderImpl.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FoxMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GoatMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ThrowableProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WolfMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/EntityEquipmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/PlayerInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/WorkbenchInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/EntityEquipmentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/PlayerInventoryMockTest.java
Labels: release/patch

#624 Support PlayerLoginEvent
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#630 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WardenMock.java
Labels: release/patch

#628 Fix MetadataTable#getMetadata NPE
  src/main/java/be/seeseemelk/mockbukkit/metadata/MetadataTable.java
Labels: release/patch

#627 Implement PluginManagerMock#removePermission(String)
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/minor

#620 Implement server icons
  src/main/java/be/seeseemelk/mockbukkit/CachedServerIconMock.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/CachedServerIconMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#634 Get default max health from AttributesMock
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
Labels: release/patch

#633 Fix compile warning in ArmorStandMockTest
  src/test/java/be/seeseemelk/mockbukkit/entity/ArmorStandMockTest.java
Labels: release/none

#632 Fix PlayerMock overriding methods it shouldn't
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#631 Remove Projectile's doesBounce implementation
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMockTest.java
Labels: release/patch

#635 Pretend swing packet gets sent
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/none

#640 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FireworkMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MobMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WardenMock.java
Labels: release/patch

#641 Don't look up host name when adding player
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
Labels: release/patch

#638 OfflinePlayerMock fixes
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMockTest.java
Labels: release/patch

#637 Send BungeeCord components as one message, not multiple
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/PlayerMessagingTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#618 Fix plugins not being properly disabled
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/patch

#622 Implement ChunkSnapshot BlockData methods
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/ChunkSnapshotMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkSnapshotMockTest.java
Labels: release/minor

#645 Stub new Methods
  src/main/java/be/seeseemelk/mockbukkit/block/state/DispenserProjectileSourceMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/persistence/PersistentDataContainerMock.java
Labels: release/patch

#636 Update Papers Maven repository URL
  build.gradle
Labels: release/none

#647 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch
