Repository MockBukkit/MockBukkit, pull requests merged in 2022-10, with the labels that each got.

#648 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
Labels: release/patch

#649 Implement Slab BlockData
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/SlabMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/SlabMockTest.java
Labels: release/minor

#651 Fix missing null check in SlabMock
  src/main/java/be/seeseemelk/mockbukkit/block/data/SlabMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/SlabMockTest.java
Labels: release/patch

#650 Implement Stairs BlockData mock
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/StairsMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/StairsMockTest.java
Labels: release/minor

#654 Implement scoreboard criteria
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/CriteriaMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/TeamMockTest.java
Labels: release/minor

#656 Remove removed entities from the server
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: release/patch

#658 Remove Useless Default Case
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: Hacktoberfest, release/patch

#659 Fix EntityMock#isDead returning the wrong Value
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: Hacktoberfest, release/patch

#662 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
Labels: release/patch

#661 Fix WorldMock#getEmptyChunkSnapshot returning an incorrect snapshot
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/patch

#643 Add Missed Tests
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldBorderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/adventure/LegacyComponentSerializerTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/AmethystClusterMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AllayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AmbientMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArmorStandMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BeeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CatMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EggMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FoxMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GoatMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MushroomCowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PigMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BrewerInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: Hacktoberfest, release/none

#665 Stub new Paper Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/BatMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BeeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EggMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MushroomCowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ProjectileMock.java
Labels: Hacktoberfest, release/patch

#639 Properly implement first/last played methods
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockPlayerListTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: Hacktoberfest, release/minor

#667 Implement Adventure's #playSound methods
  src/main/java/be/seeseemelk/mockbukkit/block/data/BedMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/sound/AudioExperience.java
  src/main/java/be/seeseemelk/mockbukkit/sound/SoundReceiver.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#670 Use BlockDataMock.mock() for internal BlockDataMock construction
  src/main/java/be/seeseemelk/mockbukkit/MockChunkData.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockChunkDataTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
Labels: release/patch

#672 Implement Visual Fire
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: release/minor

#673 Implement Gravity
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: Hacktoberfest, release/minor

#674 Implement Silence
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: Hacktoberfest, release/minor

#581 Patched renovate's config to prevent future libraryloader issues
  .github/renovate.json
  build.gradle
Labels: release/patch

#676 Add a sponsors section to the README.md
  README.md
Labels: Hacktoberfest, release/none

#678 Add Eclipse classpath and project files to gitignore
  .gitignore
Labels: Hacktoberfest, release/none

#679 Implement Campfire BlockData
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataKey.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/CampfireMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BeehiveMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/CampfireMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BeehiveMockTest.java
Labels: Hacktoberfest, release/minor

#644 Add Global Config
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/configuration/GlobalServerConfigurationTest.java
Labels: Hacktoberfest, release/minor

#531 Create a CONTRIBUTING.md
  .editorconfig
  CONTRIBUTING.md
Labels: release/none

#682 Use the default implementation for Chunk#getChunkKey
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: Hacktoberfest, release/patch
