Repository MockBukkit/MockBukkit, pull requests merged in 2022-05, with the labels that each got.

#310 Implement PlayerMock#serialize and OfflinePlayerMock#serialize
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#312 Implement the ServerMock#createBlockData methods without extra data
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#366 Implement TropicalFishBucketMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/TropicalFishBucketMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/TropicalFishBucketMetaMockTest.java
Labels: release/minor

#375 Update gradle.yml
  .github/workflows/gradle.yml
Labels: release/none

#318 Implement PlayerMock#playNote
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#377 Update gradle.yml
  .github/workflows/gradle.yml
Labels: release/none

#314 Implement some miscellaneous methods from InventoryMock
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
Labels: release/minor

#378 Remove auto code formatter
  .github/workflows/style.yml
Labels: release/none

#348 Fix JitPack build errors
  README.md
  jitpack.yml
Labels: release/none

#320 Implement methods for plugin messaging channels
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#323 Implement EntityMock#get/setLastDamageCause
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: release/minor

#325 Implement PlayerMock and EntityMock#playEffect
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#326 Implement PlayerMock#breakBlock
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#359 Don't run tests twice in GitHub actions
  .github/workflows/gradle.yml
Labels: release/none

#350 Update Docs to new Version
  docs/custom_server_mock.rst
  docs/entity_mock.rst
  docs/first_tests.rst
  docs/getting_started.rst
  docs/message_target.rst
  docs/player_mock.rst
Labels: release/none

#381 Test publish action
  .github/workflows/gradle.yml
  .github/workflows/push_tag.yml
Labels: release/none

#382 Fix push_tag.yml
  .github/workflows/push_tag.yml
Labels: release/none

#383 Fix push-tags workflow
  .github/workflows/push_tag.yml
Labels: release/none

#329 Implement chunk snapshots
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/ChunkSnapshotMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkSnapshotMockTest.java
Labels: release/minor

#384 Fix workflows
  .github/workflows/gradle.yml
  .github/workflows/push_tag.yml
Labels: release/none

#385 Do not publish package when no release label was given
  .github/workflows/push_tag.yml
Labels: release/none

#369 Implement ArmorStandMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ArmorStandMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ArmorStandMetaMockTest.java
Labels: release/minor

#386 Update publish workflow
  .github/workflows/publish.yml
Labels: release/none

#362 Fix MockUnsafeValues api verison checks
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/test/java/be/seeseemelk/mockbukkit/UnsafeValuesTest.java
Labels: release/patch

#388 Fix publish workflow (again)
  .github/workflows/gradle.yml
  .github/workflows/publish.yml
Labels: release/none

#387 Remove commons-io dependency
  build.gradle
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
Labels: release/patch

#371 Implement BannerMeta
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BannerMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/BannerMetaMockTest.java
Labels: release/minor

#390 Fix empty version error
  .github/workflows/gradle.yml
Labels: release/none

#355 Add an async catcher
  settings.gradle
  src/main/java/be/seeseemelk/mockbukkit/AsyncCatcher.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/AsyncCatcherTest.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardManagerMockTest.java
Labels: release/minor

#332 Implement world difficulty
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#392 Uncomment signing section
  build.gradle
Labels: release/none

#397 Update renovate.json
  .github/renovate.json
Labels: release/none

#401 Switch to Adoptium Temurin
  .github/workflows/gradle.yml
Labels: release/none

#351 Fix the broken Badges and remove the abandoned ones
  README.md
Labels: release/none
