Repository MockBukkit/MockBukkit, pull requests merged in 2023-05, with the labels that each got.

#693 Switch to Kotlin DSL
  .github/CODEOWNERS
  .github/workflows/gradle.yml
  build.gradle
  build.gradle.kts
  extra/TestPlugin/.gitignore
  extra/TestPlugin/build.gradle
  extra/TestPlugin/build.gradle.kts
  extra/TestPlugin/settings.gradle
  extra/TestPlugin/settings.gradle.kts
  gradle.properties
  settings.gradle
  settings.gradle.kts
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
Labels: release/none

#768 readthedocs: fix build
  .readthedocs.yml
Labels: release/none

#769 readthedocs: fix build attemp #2
  .readthedocs.yml
Labels: release/none

#770 readthedocs: fix build attempt #3
  .readthedocs.yml
Labels: release/none

#774 Add various missing methods
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FishHookMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FishHookMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMockTest.java
Labels: release/minor

#772 Make jacocoTestReport depend on test and check depend on jacocoTestReport
  build.gradle.kts
Labels: release/none

#776 Create separate build and publish pipeline
  .github/workflows/publish.yml
  .github/workflows/tag.yml
Labels: release/none

#777 Adds Minecart Entity Mocks
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CommandMinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ExplosiveMinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HopperMinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LootableMinecart.java
  src/main/java/be/seeseemelk/mockbukkit/entity/RideableMinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SpawnerMinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/StorageMinecartMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CommandMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ExplosiveMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HopperMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LootableMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PoweredMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/RideableMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SpawnerMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/StorageMinecartMockTest.java
Labels: release/minor

#778 Checkout repository to fetch tags
  .github/workflows/tag.yml
Labels: release/patch

#779 Use special token for pulling
  .github/workflows/tag.yml
Labels: release/none

#780 Fix README Badge
  README.md
Labels: release/none

#782 Fix publish by setting name in pom
  build.gradle.kts
Labels: release/none

#781 Implement Target Location API for Bats
  src/main/java/be/seeseemelk/mockbukkit/entity/BatMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BatMockTest.java
Labels: release/minor

#784 4.0 add ci
  .github/workflows/gradle.yml
Labels: 4.0
