Repository MockBukkit/MockBukkit, pull requests merged in 2023-09, with the labels that each got.

#837 Stub missing Paper methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#838 Implement noDamageTicks and getEntities methods
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: release/minor

#844 Fix onDisable function being called twice
  src/main/java/be/seeseemelk/mockbukkit/plugin/MockBukkitPluginLoader.java
Labels: release/patch

#846 Fix failing test
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: release/none

#840 Fix registry mocking not working after latest bukkit commit
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#841 Implement `getIp` and `getPort` methods on `Server`
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#828 Fix data race when scheduling a task from an async thread
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/patch

#845 Implement MockServer#unloadWorld methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
Labels: release/minor

#850 Stub Barrel LootableInventory Methods
  src/main/java/be/seeseemelk/mockbukkit/block/state/BarrelMock.java
Labels: release/none

#856 Fix: Updated SkullMetaMock to support PlayerProfile
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMockTest.java
Labels: release/minor

#839 Allows setting lines as null for a sign
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SignMockTest.java
Labels: release/patch

#858 Stop Test in LootableMinecartMockTest from randomly failing
  src/test/java/be/seeseemelk/mockbukkit/entity/LootableMinecartMockTest.java
Labels: release/none

#861 Implement RegistryMock + stubbing some methods
  src/main/java/be/seeseemelk/mockbukkit/GameEventMock.java
  src/main/java/be/seeseemelk/mockbukkit/MusicInstrumentMock.java
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SculkCatalystMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SculkShriekerMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/structure/StructureMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/structure/StructureTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMock.java
  src/main/resources/keyed/gameevent.json
  src/main/resources/keyed/musicinstrument.json
  src/main/resources/keyed/structure.json
  src/main/resources/keyed/structuretype.json
  src/main/resources/keyed/trimmaterial.json
  src/main/resources/keyed/trimpattern.json
  src/test/java/be/seeseemelk/mockbukkit/RegistryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#863 Fix Minecraft Version attribute in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: release/none

#855 Add internal tags
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTag.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagMisconfigurationException.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagParser.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagRegistry.java
  src/main/resources/internal_tags/blocks/non_solid_blocks.json
  src/main/resources/internal_tags/blocks/solid_blocks.json
  src/test/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagParserTest.java
Labels: release/minor

#859 implements the Panda entity
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PandaMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PandaMockTest.java
Labels: release/minor

#864 Make getItemFactory return an ItemFactory instead of ItemFactoryMock
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
Labels: release/patch
