Repository MockBukkit/MockBukkit, pull requests merged in 2023-04, with the labels that each got.

#748 Add Paper Methods & Fix Gradle Build
  build.gradle
  src/main/java/be/seeseemelk/mockbukkit/block/state/JukeboxMock.java
Labels: release/none

#744 fix: Set suffix instead of prefix
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
Labels: release/patch

#753 Add Paper Methods
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BellMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GuardianMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#750 Add Camel Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CamelMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CamelMockTest.java
Labels: release/minor

#756 Fix missing parameter when initializing JavaPlugin's
  src/main/java/be/seeseemelk/mockbukkit/plugin/MockBukkitConfiguredPluginClassLoader.java
Labels: release/patch

#757 Fix PlayerMock#disconnect not firing PlayerQuitEvent
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#652 Implement passenger/vehicle handling when spawning entities
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: Hacktoberfest, release/minor

#759 Add missed Tests
  src/main/java/org/bukkit/command/PluginCommandUtils.java
  src/main/java/org/bukkit/plugin/java/JavaPluginUtils.java
  src/test/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/attribute/AttributesMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataKeyTest.java
  src/test/java/be/seeseemelk/mockbukkit/boss/BossBarMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/boss/KeyedBossBarMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/help/HelpMapMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/BarrelInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ChestInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/DispenserInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/DropperInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/HopperInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ShulkerBoxInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/metadata/MetadataTableTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
  src/test/java/be/seeseemelk/mockbukkit/util/AdventureConvertsTest.java
  src/test/java/org/bukkit/command/PluginCommandUtilsTest.java
  src/test/java/org/plugin/java/JavaPluginUtilsTest.java
Labels: release/none

#764 Stub Mob Experience reward API Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/MobMock.java
Labels: release/none

#765 Fix Gamemode being desynced between HumanEntityMock and PlayerMock (#763)
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#758 Push to 3.0
  README.md
Labels: release/major

#754 Implement `PluginClassLoaderGroup`
  src/main/java/be/seeseemelk/mockbukkit/plugin/MockBukkitConfiguredPluginClassLoader.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/MockBukkitPluginClassLoaderGroup.java
  src/test/java/be/seeseemelk/mockbukkit/TestPlugin.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/MockCustomConfiguredPluginClassLoader.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/minor

#766 Update Documentation to reflect new Major Version
  docs/first_tests.rst
  docs/getting_started.rst
Labels: release/none

#767 Add Documentation for the testing for Events
  docs/events.rst
  docs/index.rst
Labels: release/none
