Repository MockBukkit/MockBukkit, pull requests merged in 2023-10, with the labels that each got.

#869 Implement Block is solid
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
Labels: release/minor

#867 Add Rabbit Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/RabbitMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/RabbitMockTest.java
Labels: release/minor

#854 Implement World PVP API
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/configuration/GlobalServerConfigurationTest.java
Labels: release/minor

#870 Assert block is of a block material
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
Labels: release/patch

#860 Add missed Tests that have been missed, harden Testcases, Deprecation Warnings
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BeaconMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/CampfireMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/ChestMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#872 Add missing Test Annotation to WorldMockTest#testGetPvpDefault
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/none

#876 Update Minecraft wiki links to new domain
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/none

#879 Add few world methods
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#878 Fix BlockState#equals
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BlockStateMockTest.java
Labels: release/patch

#882 Fix chunk unloading
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#885 Implement ChunkMock#isSlimeChunk
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: release/minor

#880 Take blockdata into consideration for the methods equals and hashCode
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BlockStateMockTest.java
Labels: release/patch

#883 Add ChunkMock#getBlocks, fix biomes
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkSnapshotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: release/minor

#886 Implement ServerMock#getCurrentTick
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: Hacktoberfest, release/minor

#889 Fix Codesmells
  src/main/java/be/seeseemelk/mockbukkit/AsyncCatcher.java
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/MapMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
  src/test/java/be/seeseemelk/mockbukkit/CoordinateTest.java
  src/test/java/be/seeseemelk/mockbukkit/RegistryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HopperMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LootableMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OcelotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PandaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/StorageMinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
Labels: Hacktoberfest, release/none

#887 ParrotMock implemented with tests
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ParrotMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ParrotMockTest.java
Labels: Hacktoberfest, release/minor

#852 Add EnderPearlMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EnderPearlMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EnderPearlMockTest.java
Labels: release/minor

#884 Implement ChunkMock#contains
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: Hacktoberfest, release/minor

#891 Add Squid Mocks
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GlowSquidMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SquidMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GlowSquidMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SquidMockTest.java
Labels: release/minor

#893 feat(entities): Implement LlamaSpitMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaSpitMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LlamaSpitMockTest.java
Labels: release/minor

#894 feat(entities): Implement DolphinMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DolphinMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DolphinMockTest.java
Labels: release/minor

#895 Add Magma Cube
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MagmaCubeMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MagmaCubeMockTest.java
Labels: release/minor

#897 Add EndermiteMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermiteMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EndermiteMockTest.java
Labels: release/minor

#898 Add Deprecation Version to @Deprecation tags
  src/main/java/be/seeseemelk/mockbukkit/MockChunkData.java
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockBukkitProfileBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockIpBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockIpBanList.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockPaperProfileBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockProfileBanList.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SkullMock.java
  src/main/java/be/seeseemelk/mockbukkit/boss/BossBarMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CamelMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DonkeyMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermanMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MuleMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OcelotMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SkeletonHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/StrayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WitherSkeletonMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieHorseMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMockTest.java
Labels: release/none
