Repository MockBukkit/MockBukkit, pull requests merged in 2023-01, with the labels that each got.

#726 Call InventoryOpenEvent
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#724 Implement powered minecart // minecart furnace
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PoweredMinecartMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PoweredMinecartMockTest.java
Labels: release/minor

#728 Minor #713 fixes
  src/main/java/be/seeseemelk/mockbukkit/block/data/SwitchMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/SwitchMockTest.java
Labels: release/patch

#730 Add getType method to poweredminecart
  src/main/java/be/seeseemelk/mockbukkit/entity/PoweredMinecartMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PoweredMinecartMockTest.java
Labels: release/patch

#688 Improve PluginManagerMock validation
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/patch

#727 Fix OpenInventoryEvent handling
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HumanEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#711 Move maintainer instructions from PR template to docs
  .github/pull_request_template.md
  docs/index.rst
  docs/maintainers.rst
Labels: release/none
