Repository MockBukkit/MockBukkit, pull requests merged in 2023-06, with the labels that each got.

#788 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ProjectileMock.java
Labels: release/patch

#790 Stubs new Methods
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMock.java
Labels: release/none

#792 Feat/update 1.20.1
  gradle.properties
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermanMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EndermanMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#796 Fix Gamerule Value not being set due to type Mismatch
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/patch

#800 Fix incorrect artifact name
  build.gradle.kts
  settings.gradle.kts
Labels: release/patch

#802 Select component for which to publish artifacts
  build.gradle.kts
Labels: release/patch
