Repository MockBukkit/MockBukkit, pull requests merged in 2023-07, with the labels that each got.

#804 Implement Llama caravan API
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LlamaMockTest.java
Labels: release/minor

#807 chore(stubs/ban)!: Add Method Stubs and rework Bans to make project compile
  src/main/java/be/seeseemelk/mockbukkit/MockBanList.java
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockIpBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockIpBanList.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockProfileBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockProfileBanList.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockBanListTest.java
  src/test/java/be/seeseemelk/mockbukkit/MockBanList_MockBanEntryListTest.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockIpBanEntryTest.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockIpBanListTest.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockProfileBanEntryTest.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockProfileBanListTest.java
Labels: release/minor

#801 chore(tests): Add missing tests
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMock.java
  src/test/java/be/seeseemelk/mockbukkit/EnchantmentTests.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GoatMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MinecartMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MonsterMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/VehicleMockTest.java
Labels: release/none

#799 Send WorldGameRuleChangeEvent on Gamerule Change
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/patch

#803 feat(entities): Implement Agelock API for Tadpoles
  src/main/java/be/seeseemelk/mockbukkit/entity/TadpoleMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TadpoleMockTest.java
Labels: release/minor

#809 Allow project members to approve Gradle changes
  .github/CODEOWNERS
Labels: release/none

#797 BukkitSchedulerMock.java add missing methods
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/minor

#360 Implement reloading
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/attribute/AttributeInstanceMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/metadata/MetadataTable.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTask.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/metadata/MetadataTableTest.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/minor

#806 Add Adventure BossBar viewing
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#798 Add Adventure docs
  docs/adventure.rst
  docs/index.rst
Labels: release/none

#808 Refresh Gradle dependencies when building
  .github/workflows/publish.yml
Labels: release/none

#811 implements ServerMock.getRegistry
  src/main/java/be/seeseemelk/mockbukkit/ReflectionAccessException.java
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#819 Fix the Ban System again (Migration to Paper Profiles)
  src/main/java/be/seeseemelk/mockbukkit/ban/MockBukkitProfileBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockPaperProfileBanEntry.java
  src/main/java/be/seeseemelk/mockbukkit/ban/MockProfileBanList.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockBukkitProfileBanEntryTest.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockPaperProfileBanEntryTest.java
  src/test/java/be/seeseemelk/mockbukkit/ban/MockProfileBanListTest.java
Labels: release/minor

#815 Fix some code smells
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/ChunkSnapshotMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LlamaMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LootableMinecart.java
  src/main/java/be/seeseemelk/mockbukkit/entity/data/EntityDataRegistry.java
Labels: release/patch

#820 Implement runAtFixedRate
  src/main/java/be/seeseemelk/mockbukkit/scheduler/paper/FoliaAsyncScheduler.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/paper/FoliaAsyncSchedulerTest.java
Labels: release/minor

#823 Fix runTaskLaterAsync and runTaskTimerAsync not clamping delay
  src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
Labels: release/patch

#816 Implement UnsafeValues#fromLegacy for non-legacy materials
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/test/java/be/seeseemelk/mockbukkit/UnsafeValuesTest.java
Labels: release/minor

#786 Documentation additions
  README.md
Labels: enhancement, release/none

#824 Implement getNearbyEntities
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#821 Add main Contributors to POM
  build.gradle.kts
Labels: release/none

#826 Implement AreaEffectCloud Entity
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AreaEffectCloudMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AreaEffectCloudMockTest.java
Labels: release/minor
