Repository MockBukkit/MockBukkit, pull requests merged in 2024-05, with the labels that each got.

#1004 Fix isAction check returning true in other people's CI
  build.gradle.kts
Labels: release/none

#1005 Fix locale issues
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/data/EntityDataRegistry.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTag.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagParser.java
  src/test/java/be/seeseemelk/mockbukkit/entity/data/EntityDataRegistryTest.java
  src/test/java/be/seeseemelk/mockbukkit/tags/RegistryTest.java
  src/test/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagParserTest.java
Labels: release/patch

#1009 Add sign side implementation
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SignMockTest.java
Labels: release/minor

#1014 Add Support for ItemStack#deserializeBytes & ItemStack#serializeAsBytes and complete ItemMetaSerialization
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ArmorStandMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/AxolotlBucketMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BannerMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BundleMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CompassMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CrossbowMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/EnchantedBookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkEffectMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/KnowledgeBookMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/LeatherArmorMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/MapMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SpawnEggMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SuspiciousStewMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/TropicalFishBucketMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMock.java
  src/main/java/be/seeseemelk/mockbukkit/util/io/BukkitObjectInputStreamMock.java
  src/main/java/be/seeseemelk/mockbukkit/util/io/BukkitObjectOutputStreamMock.java
  src/test/java/be/seeseemelk/mockbukkit/UnsafeValuesTest.java
Labels: release/minor

#1018 Fix Material#getKey usage
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
Labels: release/patch
