Repository MockBukkit/MockBukkit, pull requests merged in 2024-10, with the labels that each got.

#881 Fix AsyncPlayerPreLoginEvent and PlayerLoginEvent to respect login result
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: Hacktoberfest, release/patch

#1139 Add a builder for MockPlugin
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/MockPlugin.java
  src/test/java/be/seeseemelk/mockbukkit/MockPluginTest.java
Labels: release/minor

#1149 feat(ci): Upload test results to codecov
  .github/workflows/coverage.yaml
  codecov.yml
Labels: release/none

#1148 Cleanup the build workflow
  .github/workflows/build.yml
  .github/workflows/coverage.yaml
  .github/workflows/publish.yml
  gradlew.bat
Labels: release/none

#1144 Disable missing JavaDoc warnings, other JavaDoc settings cleanup
  build.gradle.kts
Labels: release/none

#929 Create URLClassLoader for plugins loaded from jar file
  extra/TestPlugin/src/main/resources/config.yml
  extra/TestPlugin/src/main/resources/plugin.yml
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/MockBukkitConfiguredPluginClassLoader.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/MockBukkitURLClassLoader.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
  src/test/java/be/seeseemelk/mockbukkit/plugin/MockBukkitURLClassLoaderTest.java
Labels: release/minor

#1051 feat(itemtype): Implement more ItemType Methods
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemTypeMock.java
  src/main/resources/keyed/item.json
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemTypeMockTest.java
Labels: release/minor

#1150 Updated code curly bracket to match correct style
  src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
  src/main/java/be/seeseemelk/mockbukkit/conversations/ConversationTracker.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EnderCrystalMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EvokerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HoglinMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/InteractionMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemFrameMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/main/java/be/seeseemelk/mockbukkit/util/OldEnumMock.java
  src/test/java/be/seeseemelk/mockbukkit/PermissionManagerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/RaidMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/SignMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DrownedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EnderCrystalMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HoglinMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PillagerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/RaiderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SnowmanMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ZombieMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemStackMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/PlayerInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/ActivePotionEffectTest.java
Labels: release/none

#1151 Added unit tests to existing code
  src/test/java/be/seeseemelk/mockbukkit/ChunkCoordinateTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TameableAnimalMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/event/EventFactoryMockTest.java
Labels: release/none

#1155 chore(offlineplayer): stub method in OfflinePlayerMock
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
Labels: release/none

#1157 Fix unloadWorld returning false when WorldUnloadEvent is not cancelled
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/patch

#1160 Implement ChunkMock.getChunkKey
  src/main/java/org/mockbukkit/mockbukkit/ChunkMock.java
Labels: 4.0

#1143 Remove ListenerEntry
  src/main/java/org/mockbukkit/mockbukkit/plugin/ListenerEntry.java
Labels: 4.0

#1164 Rename all remaining mock classes from Mock* to *Mock
  src/main/java/org/mockbukkit/mockbukkit/MockBukkit.java
  src/main/java/org/mockbukkit/mockbukkit/PlayerListMock.java
  src/main/java/org/mockbukkit/mockbukkit/PluginMock.java
  src/main/java/org/mockbukkit/mockbukkit/UnsafeValuesMock.java
  src/main/java/org/mockbukkit/mockbukkit/ban/IpBanEntryMock.java
  src/main/java/org/mockbukkit/mockbukkit/ban/IpBanListMock.java
  src/main/java/org/mockbukkit/mockbukkit/ban/PaperProfileBanEntryMock.java
  src/main/java/org/mockbukkit/mockbukkit/ban/ProfileBanListMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/food/FoodConsumption.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/CustomConfiguredPluginClassLoaderMock.java
  src/main/java/org/mockbukkit/mockbukkit/potion/InternalPotionDataMock.java
  src/test/java/org/mockbukkit/mockbukkit/MockBukkitTest.java
  src/test/java/org/mockbukkit/mockbukkit/PluginMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/ServerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/TestPlugin.java
  src/test/java/org/mockbukkit/mockbukkit/WorldBorderMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/WorldMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/ban/IpBanEntryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/ban/IpBanListMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/ban/PaperProfileBanEntryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/ban/ProfileBanListMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/EntityMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/metadata/MetadataTableTest.java
  src/test/java/org/mockbukkit/mockbukkit/scheduler/paper/FoliaAsyncSchedulerTest.java
Labels: 4.0

#1165 Rename BambooMock to BambooDataMock
  src/main/java/org/mockbukkit/mockbukkit/block/data/BambooDataMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BambooDataMockTest.java
Labels: 4.0

#1171 Add getOrThrow method to RegistryMock
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/test/java/be/seeseemelk/mockbukkit/RegistryMockTest.java
Labels: release/patch

#1166 Add for removal annotation to assert* method
  src/main/java/org/mockbukkit/mockbukkit/command/MessageTarget.java
  src/main/java/org/mockbukkit/mockbukkit/entity/AbstractSkeletonMock.java
Labels: 4.0
