Repository MockBukkit/MockBukkit, pull requests merged in 2024-08, with the labels that each got.

#1046 Impemented ServerMock::getTags
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#1062 chore(update): Update Mockbukkit to latest Paper 1.21 build
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/banner/PatternTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ShieldMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/registry/RegistryAccessMock.java
  src/main/resources/keyed/attribute.json
  src/main/resources/keyed/banner_pattern.json
  src/main/resources/keyed/block.json
  src/main/resources/keyed/damage_type.json
  src/main/resources/keyed/enchantment.json
  src/main/resources/keyed/entity_type.json
  src/main/resources/keyed/game_event.json
  src/main/resources/keyed/item.json
  src/main/resources/keyed/jukebox_song.json
  src/main/resources/keyed/mob_effect.json
  src/main/resources/keyed/painting_variant.json
  src/main/resources/keyed/potion.json
  src/main/resources/keyed/trim_material.json
  src/main/resources/keyed/trim_pattern.json
  src/main/resources/keyed/worldgen/biome.json
  src/main/resources/registries/registry_key_class_relation.json
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ShieldMetaMockTest.java
Labels: release/minor

#1059 feat: add support for getBasePotionType and setBasePotionType (new)
  src/main/java/be/seeseemelk/mockbukkit/entity/AreaEffectCloudMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/PotionUtils.java
  src/main/resources/potion/type_mapping/extendable.json
  src/main/resources/potion/type_mapping/upgradeable.json
  src/test/java/be/seeseemelk/mockbukkit/entity/AreaEffectCloudMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArrowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/PotionUtilsTest.java
Labels: release/minor

#1061 Unit tests and fixes for get eye height
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DrownedMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EndermanMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HoglinMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZombieMock.java
  src/main/resources/entities/mooshroom.json
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BeeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CatMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ChickenMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/CowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DolphinMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DonkeyMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DrownedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EndermanMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FoxMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GoatMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HoglinMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LlamaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MuleMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MushroomCowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OcelotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PandaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PigMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PolarBearMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PufferFishMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/RabbitMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SheepMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SkeletonHorseMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TurtleMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WolfMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ZombieMockTest.java
Labels: release/patch

#1066 Adds Ender Crystal Mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EnderCrystalMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EnderCrystalMockTest.java
Labels: release/minor

#1067 Implemented EnchantmentMock.canEnchantItem() for vanilla enchantments
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/resources/keyed/enchantment.json
  src/test/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMockTest.java
Labels: release/minor

#1068 Added mocks for Raid and Raider
  src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/RaiderMock.java
  src/test/java/be/seeseemelk/mockbukkit/RaidMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/RaiderMockTest.java
Labels: release/minor

#1072 Added mocks for Illager and Pillager
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/IllagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PillagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ChestInventoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PillagerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ChestInventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
Labels: release/minor

#1073 Added mocks for Witch and Ravager
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EnderCrystalMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/RavagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WitchMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EnderCrystalMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/RavagerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WitchMockTest.java
Labels: release/minor

#1074 Added mocks for Spellcaster and Vindicator
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SpellcasterMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/VindicatorMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SpellcasterMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/VindicatorMockTest.java
Labels: release/minor

#1079 Added mocks for Golems (Iron Golem, Snowman and Shulker)
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/CreatureMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GolemMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/IronGolemMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ShulkerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SnowmanMock.java
  src/main/resources/entities/snow_golem.json
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GolemMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/IronGolemMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ShulkerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SnowmanMockTest.java
Labels: release/minor

#1081 docs(getting_started): Updated to Minecraft 1.21
  docs/conf.py
  docs/getting_started.rst
  docs/requirements.txt
Labels: release/none

#1082 Refactor messaging system
  src/main/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMock.java
  src/main/java/be/seeseemelk/mockbukkit/conversations/ConversationTracker.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/command/ConsoleCommandSenderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/conversations/ConversationTrackerTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#1084 Implemented entities ItemFrame and GlowItemFrame
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/GlowItemFrameMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemFrameMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GlowItemFrameMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ItemFrameMockTest.java
Labels: release/minor

#1086 feat(entities): Add ArmadilloMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmadilloMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArmadilloMockTest.java
Labels: release/minor

#1087 feat(enchantments): Implement translation keys and anvil cost
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/test/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMockTest.java
Labels: release/minor

#1092 Remove `minecraft:` string from translation key in enchantment mock
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/test/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMockTest.java
Labels: release/patch

#1091 Added logic for BambooMock
  src/main/java/be/seeseemelk/mockbukkit/block/data/BambooMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/data/BambooMockTest.java
Labels: release/minor

#1094 Translation keys for remaining keyed mocks
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMock.java
  src/test/java/be/seeseemelk/mockbukkit/damage/DamageSourceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/damage/DamageTypeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMockTest.java
Labels: release/minor

#1093 Add translation keys for potion effect types
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
Labels: release/minor

#1097 Make update commands method into no operation
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#1063 Feat/1.21.1
  build.gradle.kts
  gradle.properties
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BoatMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CompassMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/FireworkMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/resources/keyed/enchantment.json
Labels: release/minor

#1077 Plain text component language codes
  src/main/java/be/seeseemelk/mockbukkit/adventure/JsonBackedLanguage.java
  src/main/java/be/seeseemelk/mockbukkit/adventure/Language.java
  src/main/java/be/seeseemelk/mockbukkit/adventure/Languages.java
  src/main/java/be/seeseemelk/mockbukkit/adventure/PlainTextComponentProviderImpl.java
  src/main/resources/META-INF/services/net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer$Provider
  src/main/resources/translations/en-us.json
  src/test/java/be/seeseemelk/mockbukkit/adventure/PlainTextComponentProviderImplTest.java
Labels: release/patch

#1099 fix(player): Throw UnsupportedOperationException when calling remove()
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#1065 Backport #1059 to the 1.20 branch
  src/main/java/be/seeseemelk/mockbukkit/entity/AreaEffectCloudMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/PotionUtils.java
  src/main/resources/potion/type_mapping/extendable.json
  src/main/resources/potion/type_mapping/upgradeable.json
  src/test/java/be/seeseemelk/mockbukkit/entity/AreaEffectCloudMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArrowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/PotionUtilsTest.java
Labels: release/none
