Repository MockBukkit/MockBukkit, pull requests merged in 2024-02, with the labels that each got.

#957 Add PigZombieMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PigZombieMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PigZombieMockTest.java
Labels: release/minor

#960 Fix WorkbenchInventoryMock#setMatrix
  src/main/java/be/seeseemelk/mockbukkit/inventory/WorkbenchInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/WorkbenchInventoryMockTest.java
Labels: release/patch

#909 feat(world & server): Implement Spawn Limit API
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
Labels: release/minor

#966 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/ConduitMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/lifecycle/event/MockLifecycleEventManager.java
Labels: release/patch

#965 Implement translation keys
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/test/java/be/seeseemelk/mockbukkit/UnsafeValuesTest.java
Labels: release/minor

#963 Merge to 4.0 merge from 1.20
  .github/workflows/publish.yml
  build.gradle.kts
  extra/TestPlugin/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/mockbukkit/mockbukkit/PlayerListMock.java
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/UnsafeValuesMock.java
  src/main/java/org/mockbukkit/mockbukkit/WorldMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/configuration/ServerConfiguration.java
  src/main/java/org/mockbukkit/mockbukkit/entity/BoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ChickenMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PigZombieMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/TNTPrimedMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/WorkbenchInventoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/potion/PotionEffectTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/profile/PlayerProfileMock.java
  src/test/java/org/mockbukkit/mockbukkit/PlayerListMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/ServerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/WorldMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/BoatMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/ChestBoatMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/ChickenMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PigZombieMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/WorkbenchInventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/SkullMetaMockTest.java
Labels: 4.0

#968 Stub methods, fix loads of issues
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageEffectMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageSourceBuilderMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageSourceMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MushroomCowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/resources/keyed/damagetype.json
  src/test/java/be/seeseemelk/mockbukkit/WorldBorderMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#969 Implement ChunkMock isForceLoaded
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/test/java/be/seeseemelk/mockbukkit/ChunkTest.java
Labels: release/minor

#970 BlockMock | Light level, LightFromSky and LightFromBlocks
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
Labels: release/minor

#974 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreMock.java
Labels: release/patch

#958 Implementation of all subinterfaces of AbstractArrow
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/SpectralArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TridentMock.java
  src/main/resources/entities/arrow.json
  src/main/resources/entities/spectral_arrow.json
  src/main/resources/entities/trident.json
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/AbstractArrowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArrowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/SpectralArrowMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TridentMockTest.java
Labels: release/minor

#959 Implement BlockDisplay and ItemDisplay
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BlockDisplayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/DisplayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemDisplayMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BlockDisplayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/DisplayMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ItemDisplayMockTest.java
Labels: release/minor

#973 Unit tests for DamageSourceMock
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageSourceMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageTypeMock.java
  src/test/java/be/seeseemelk/mockbukkit/damage/DamageSourceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/damage/DamageTypeMockTest.java
Labels: release/patch

#979 Stub methods in sign mock
  src/main/java/be/seeseemelk/mockbukkit/block/state/SignMock.java
Labels: release/patch

#975 Implement blocking logic for HumanEntityMock
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/PlayerInventoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HumanEntityMockTest.java
Labels: release/minor

#976 Add `Marker` mock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/MarkerMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MarkerMockTest.java
Labels: release/minor

#980 Adjusted code style
  src/main/java-templates/be/seeseemelk/mockbukkit/BuildParameters.java.peb
  src/main/java/be/seeseemelk/mockbukkit/AsyncCatcher.java
  src/main/java/be/seeseemelk/mockbukkit/GameEventMock.java
  src/main/java/be/seeseemelk/mockbukkit/MockBukkitExtension.java
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BlockStateMock.java
  src/main/java/be/seeseemelk/mockbukkit/configuration/ServerConfiguration.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageSourceMock.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractProjectileMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AllayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChestBoatMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ItemDisplayMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/StorageMinecartMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/TNTPrimedMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/structure/StructureTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockInternalPotionData.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerTexturesMock.java
  src/main/java/be/seeseemelk/mockbukkit/scheduler/ScheduledTask.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTag.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagMisconfigurationException.java
  src/main/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagParser.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/damage/DamageSourceMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/enchantment/EnchantmentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FishHookMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/GlowSquidMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/MagmaCubeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/OcelotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PandaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TNTPrimedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryViewMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/none
