Repository MockBukkit/MockBukkit, pull requests merged in 2024-01, with the labels that each got.

#940 fix BlockMock.setType(Material type, boolean applyPhysics) doing nothing
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
Labels: release/patch

#931 Update to 1.20.4
  gradle.properties
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/CreatureSpawnerMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SpawnEggMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/persistence/PersistentDataContainerMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockInternalPotionData.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ObjectiveMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreMock.java
  src/main/resources/internal_tags/blocks/non_solid_blocks.json
  src/main/resources/internal_tags/blocks/solid_blocks.json
  src/main/resources/keyed/enchantment.json
  src/main/resources/keyed/gameevent.json
  src/main/resources/keyed/musicinstrument.json
  src/main/resources/keyed/potioneffecttype.json
  src/main/resources/keyed/structure.json
  src/main/resources/keyed/structuretype.json
  src/main/resources/keyed/trimmaterial.json
  src/main/resources/keyed/trimpattern.json
  src/main/resources/tags/blocks/replaceable_plants.json
  src/test/java/be/seeseemelk/mockbukkit/ChunkSnapshotMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/EnchantmentTests.java
  src/test/java/be/seeseemelk/mockbukkit/MockChunkDataTest.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/block/BlockMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/enchantment/EnchantmentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/EnchantedBookMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/EnchantmentMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectTypeTest.java
  src/test/java/be/seeseemelk/mockbukkit/tags/internal/InternalTagParserTest.java
Labels: release/minor

#927 feat(entities): Implement LeashHitch Entity
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LeashHitchMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LeashHitchMockTest.java
Labels: release/minor

#930 Add TNTPrimed Mock and Tests
  src/main/java/be/seeseemelk/mockbukkit/entity/TNTPrimedMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/TNTPrimedMockTest.java
Labels: release/minor

#933 Implement PlayerTextures in playerprofilemock
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerTexturesMock.java
  src/test/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/profile/PlayerTexturesMockTest.java
Labels: release/minor

#943 fix npe when hashing skullmetamock
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
Labels: release/patch

#942 feat(bans): Implement rest of ipban methods in server and add coverage for related methods
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#944 fix playerlist hasplayedbefore
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/test/java/be/seeseemelk/mockbukkit/MockPlayerListTest.java
Labels: release/minor

#945 Implemented more methods in SkullMetaMock and PotionEffectType
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/main/java/be/seeseemelk/mockbukkit/profile/PlayerProfileMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/SkullMetaMockTest.java
Labels: release/minor

#925 feat(entities): Implement Rest of Chicken Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ChickenMockTest.java
Labels: release/minor

#951 chore(stubbing): Stub Paper Methods
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
Labels: release/none

#947 Implement getOfflinePlayerIfCached with tests
  src/main/java/be/seeseemelk/mockbukkit/MockPlayerList.java
  src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
  src/test/java/be/seeseemelk/mockbukkit/ServerMockTest.java
Labels: release/minor

#851 Adds Mocks for both Boat and ChestBoat
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BoatMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ChestBoatMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BoatMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ChestBoatMockTest.java
Labels: release/minor
