Repository MockBukkit/MockBukkit, pull requests merged in 2024-06, with the labels that each got.

#1021 Fix JitPack
  jitpack.yml
Labels: release/none

#1024 chore(update): Update upstream
  src/main/java/be/seeseemelk/mockbukkit/ChunkMock.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/FireballMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
Labels: release/minor

#1029 feat(intellij): Add Project Icon in IntelliJ
  .gitignore
  .idea/icon.png
Labels: release/none

#1027 feat(fireball): Implement new acceleration and power Methods for Fireball
  src/main/java/be/seeseemelk/mockbukkit/entity/FireballMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/FireballMockTest.java
Labels: release/minor

#1026 feat(player): Implement new spawnParticle Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/minor

#1030 fix: make itemmeta also copy the maxDamage if exists
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
Labels: release/patch

#1031 chore(git): Add Kotlin LSP Database file to gitignore
  .gitignore
Labels: release/none
