Repository MockBukkit/MockBukkit, pull requests merged in 2024-07, with the labels that each got.

#1037 Stub method
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
Labels: release/patch

#1036 Enhance simulateConsumeItem to apply inflicted status effects gained from consumption
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/food/FoodConsumption.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockInternalPotionData.java
  src/main/resources/foods/food_properties.json
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/food/FoodConsumptionLoadTest.java
Labels: release/minor

#1044 Update username to use user token instead of username
  .github/workflows/publish.yml
Labels: release/patch

#1045 Update user token again
  .github/workflows/publish.yml
Labels: release/patch

#994 Update README.md
  README.md
Labels: release/none

#1043 feat(player): Entity visibility
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#986 Make Entity#removePassenger(Entity) remove passenger
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
Labels: release/patch

#1050 chore(paper): Stub Paper Methods
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractArrowMock.java
Labels: release/none

#1048 Implement logic for EntityMock, LivingEntityMock, ArmorStandMock, HumanEntityMock and PlayerMock
  src/main/java/be/seeseemelk/mockbukkit/entity/ArmorStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HumanEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ArmorStandMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HumanEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#1053 Fix ActivePotionEffect#hasExpired calculation
  src/main/java/be/seeseemelk/mockbukkit/potion/ActivePotionEffect.java
  src/test/java/be/seeseemelk/mockbukkit/potion/ActivePotionEffectTest.java
Labels: release/patch

#1054 fix(docs): Specify required packages explicitly
  .readthedocs.yml
  docs/conf.py
  docs/requirements.txt
Labels: release/none
