Repository MockBukkit/MockBukkit, pull requests merged in 2024-11, with the labels that each got.

#1174 Remove remaining runtime exceptions
  src/main/java/org/mockbukkit/mockbukkit/MockBukkit.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/org/mockbukkit/mockbukkit/MockBukkitTest.java
  src/test/java/org/mockbukkit/mockbukkit/plugin/PluginManagerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: 4.0

#1176 Remove experimental annotation from MockBukkitExtension
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitInject.java
Labels: 4.0

#1182 Update v4 branch with v1.21 features
  build.gradle.kts
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryMock.java
  src/test/java/org/mockbukkit/mockbukkit/registry/RegistryMockTest.java
Labels: 4.0

#1181 Added compatibility between MockBukkitExtension and Nested classes
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
  src/test/java/org/mockbukkit/mockbukkit/MockBukkitExtensionTest.java
Labels: 4.0

#1185 Change publishing plugin
  .github/workflows/publish.yml
  build.gradle.kts
Labels: 4.0

#1194 Change mockbukkit version badge link search value
  README.md
Labels: release/none

#1186 Remove 4.0 workflow (LAST STEP)
  .github/workflows/gradle.yml
Labels: release/none, 4.0

#1197 chore(docs): remove docs
  docs/.gitignore
  docs/Makefile
  docs/_static/.gitkeep
  docs/_templates/.gitkeep
  docs/adventure.rst
  docs/conf.py
  docs/custom_server_mock.rst
  docs/dependencies.rst
  docs/entity_mock.rst
  docs/events.rst
  docs/first_tests.rst
  docs/getting_started.rst
  docs/index.rst
  docs/maintainers.rst
  docs/make.bat
  docs/message_target.rst
  docs/player_mock.rst
  docs/requirements.txt
  docs/scheduler_mock.rst
  docs/world_mock.rst
Labels: release/none

#1187 Fix ItemMetaMock get enchants
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
Labels: release/minor

#1183 Fix data races in scheduler, plugin manager and player list
  src/main/java/org/mockbukkit/mockbukkit/PlayerListMock.java
  src/main/java/org/mockbukkit/mockbukkit/ban/IpBanListMock.java
  src/main/java/org/mockbukkit/mockbukkit/ban/ProfileBanListMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/org/mockbukkit/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/main/java/org/mockbukkit/mockbukkit/scheduler/RepeatingTask.java
  src/main/java/org/mockbukkit/mockbukkit/scheduler/ScheduledTask.java
Labels: release/patch

#1179 Implementation of `InventoryViewMock::getItem` and `InventoryViewMock::setItem` (to 4.0 branch)
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryViewMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/SimpleInventoryViewMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/InventoryViewMockTest.java
Labels: release/minor

#1188 Patches for ItemMetaMock and ItemStackMock
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ArmorMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ArmorStandMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/AxolotlBucketMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/BannerMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/BookMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/BundleMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ColorableArmorMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/CompassMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/CrossbowMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/EnchantmentStorageMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/FireworkEffectMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/FireworkMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/KnowledgeBookMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/LeatherArmorMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/MapMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/OminousBottleMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ShieldMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/SkullMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/SpawnEggMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/SuspiciousStewMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/TropicalFishBucketMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/ThrownPotionMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ColorableArmorMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/EnchantmentStorageMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/LeatherArmorMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/util/UnsafeValuesTest.java
Labels: release/minor

#1202 Make extension always ensure there is a mock instance available
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/SwitchDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemFactoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/util/UnsafeValuesTest.java
Labels: release/patch

#1201 Updated brackets to be in the correct line
  src/main/java/org/mockbukkit/mockbukkit/command/CommandResult.java
  src/main/java/org/mockbukkit/mockbukkit/entity/AllayMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/matcher/entity/human/HumanEntityInventoryViewItemMatcher.java
  src/main/java/org/mockbukkit/mockbukkit/matcher/inventory/ItemSimilarityMatcher.java
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/EndGatewayStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/matcher/command/CommandResultSucceedMatcherTest.java
  src/test/java/org/mockbukkit/mockbukkit/matcher/inventory/InventoryItemAmountMatcherTest.java
  src/test/java/org/mockbukkit/mockbukkit/registry/RegistryMockTest.java
Labels: release/none

#1205 Updated brackets to be in the correct line (Cont.)
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ArmorMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/LeatherArmorMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/OminousBottleMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ColorableArmorMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/LeatherArmorMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/util/UnsafeValuesTest.java
Labels: release/none

#1208 Add GetEntityCount and GetMoonPhase in WorldMock
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1207 fix(codecov): remove codecov_yml_path flag on coverage job
  .github/workflows/coverage.yaml
Labels: release/none

#1204 Fix equals and implement missing ItemStackMock methods
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/persistence/PersistentDataContainerViewMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/persistence/PersistentDataContainerViewMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/persistence/PersistentDataTest.java
Labels: release/minor

#1210 Implement blockdata reading
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/BlockTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BambooDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BlockDataKeyTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockTest.java
  src/test/resources/blockData/invalidSerializations.json
  src/test/resources/blockData/validSerializations.json
Labels: release/minor

#1216 Implement fence data
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/FenceDataMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/FenceDataMockTest.java
Labels: release/minor
