Repository MockBukkit/MockBukkit, pull requests merged in 2024-09, with the labels that each got.

#1100 Boss bar implementation
  src/main/java/be/seeseemelk/mockbukkit/boss/BossBarImplementationMock.java
  src/main/java/be/seeseemelk/mockbukkit/boss/BossBarImplementationProvider.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/resources/META-INF/services/net.kyori.adventure.bossbar.BossBarImplementation$Provider
  src/test/java/be/seeseemelk/mockbukkit/boss/BossBarImplementationMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#1089 feat(entities): Implement endersignal entity
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EnderSignalMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EnderSignalMockTest.java
Labels: release/minor

#1108 Implemented get enchantments method in item stack
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemStackMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemStackMockTest.java
Labels: release/patch

#902 Fix constructor call
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
Labels: release/patch

#1114 Remove method removed from the api
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
Labels: release/patch

#1119 Stub methods in UnsafeValuesMock
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
Labels: release/patch

#1116 Implemented `TeamMock#audiences()`
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/test/java/be/seeseemelk/mockbukkit/scoreboard/TeamMockTest.java
Labels: release/minor

#1112 Implemented collidesAt and wouldCollideUsing
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#1110 Implemented entities Evoker Fangs and Interaction
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EvokerFangsMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/InteractionMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EvokerFangsMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/InteractionMockTest.java
Labels: release/minor

#1120 Revert "chore(deps): update dependency gradle to v8.10.1"
  extra/TestPlugin/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: release/none

#1115 Implemented logic for launch projectile in living entity
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/minor

#1122 Implemented entity ThrownPotion
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ThrownPotionMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ThrownPotionMockTest.java
Labels: release/minor

#1107 Create new `Build` workflow without unused scripts
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: release/none

#1123 Allow bug reports for 1.21
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: release/none

#1103 [House keeping] Mitigate project code smells
  src/main/java/be/seeseemelk/mockbukkit/PermissionManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/adventure/Languages.java
  src/main/java/be/seeseemelk/mockbukkit/damage/DamageTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/scoreboard/TeamMock.java
  src/test/java/be/seeseemelk/mockbukkit/adventure/LanguagesTest.java
  src/test/java/be/seeseemelk/mockbukkit/damage/DamageTypeMockTest.java
Labels: release/none

#1118 Remove version from readme
  README.md
Labels: release/none

#1076 Fix item serialization tests and item serialization
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ArmorMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BannerMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ColorableArmorMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/PotionMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ShieldMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/UnsafeValuesTest.java
  src/test/resources/itemstack/metaItemTypes.json
Labels: release/patch

#1109 Implemented entities Husk and Bogged
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BoggedMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/HuskMock.java
  src/main/resources/entities/husk.json
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BoggedMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/HuskMockTest.java
Labels: release/minor

#1034 feat(loading): Implement custom config loading
  build.gradle.kts
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
  src/test/resources/loadWithConfig/config_test.yml
Labels: release/minor

#1125 Implemented missing stubs
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/MenuTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/registry/RegistryAccessMock.java
  src/main/resources/keyed/menu.json
  src/main/resources/registries/registry_key_class_relation.json
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/patch

#1127 Added entity Zoglin
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/ZoglinMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/ZoglinMockTest.java
Labels: release/minor

#1128 Fix getEnchantmentLevel
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemStackMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemStackMockTest.java
Labels: release/minor

#1133 Stub method in ItemFactory (enchantWithLevels)
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemFactoryMock.java
Labels: release/patch

#1136 Stub for methods
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/BrewingStandMockTest.java
Labels: release/patch

#1138 Stub methods in WorldMock
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
Labels: release/patch

#1135 Removed concurrency from test longRunningTask_Throws_RunTimeException
  src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/none

#1126 Implemented mocks for Breeze, WindCharge and BreezeWindCharge
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractWindChargeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BreezeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/BreezeWindChargeMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/WindChargeMock.java
  src/main/java/be/seeseemelk/mockbukkit/event/EventFactoryMock.java
  src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BreezeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/BreezeWindChargeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/WindChargeMockTest.java
Labels: release/minor

#1058 Add more tests to item stack class with fixes to those tests
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemStackMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BundleMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/CrossbowMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/OminousBottleMetaMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/TropicalFishBucketMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/block/state/CampfireMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemStackMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/CrossbowMetaMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/ItemMetaMockTest.java
  src/test/resources/itemstack/setType.json
Labels: release/patch

#1140 Fix isSimilar
  src/main/java/be/seeseemelk/mockbukkit/inventory/ItemStackMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/ItemStackMockTest.java
Labels: release/patch
