Repository MockBukkit/MockBukkit, pull requests merged in 2024-04, with the labels that each got.

#988 Stub new methods
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/minor

#989 Use the same Java version in the test plugin as used in the root project
  build.gradle.kts
  extra/TestPlugin/build.gradle.kts
  gradle.properties
Labels: release/none

#984 Print stack trace when logging errors
  src/main/resources/logger.properties
Labels: release/patch

#990 Add createMockPlugin overload with version parameter
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/test/java/be/seeseemelk/mockbukkit/MockBukkitTest.java
Labels: release/minor

#996 Stub methods and registry fixes
  src/main/java/be/seeseemelk/mockbukkit/MockUnsafeValues.java
  src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AbstractArrowMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/AgeableMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/LivingEntityMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/main/resources/keyed/enchantment.json
  src/main/resources/keyed/trimmaterial.json
  src/main/resources/keyed/trimpattern.json
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMockTest.java
Labels: release/minor

#995 More verbose error message.
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
Labels: release/patch

#997 Constructors for keyed classes
  src/main/java/be/seeseemelk/mockbukkit/GameEventMock.java
  src/main/java/be/seeseemelk/mockbukkit/MusicInstrumentMock.java
  src/main/java/be/seeseemelk/mockbukkit/RegistryMock.java
  src/main/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/structure/StructureMock.java
  src/main/java/be/seeseemelk/mockbukkit/generator/structure/StructureTypeMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMock.java
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMock.java
  src/main/java/be/seeseemelk/mockbukkit/potion/MockPotionEffectType.java
  src/test/java/be/seeseemelk/mockbukkit/GameEventMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/MusicInstrumentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/enchantments/EnchantmentMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/generator/structure/StructureMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/generator/structure/StructureTypeMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimMaterialMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/trim/TrimPatternMockTest.java
Labels: release/minor

#998 Implementing respawn location.
  src/main/java/be/seeseemelk/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#999 Implemented BookMetaMock::setGeneration
  src/main/java/be/seeseemelk/mockbukkit/inventory/meta/BookMetaMock.java
  src/test/java/be/seeseemelk/mockbukkit/inventory/meta/BookMetaMockTest.java
Labels: release/minor

#1001 Implemented BlockDataMock::getAsString(boolean)
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMock.java
  src/main/java/be/seeseemelk/mockbukkit/block/data/BlockDataMockRegistry.java
  src/main/resources/materials/material_data.json
  src/test/java/be/seeseemelk/mockbukkit/block/data/BlockDataMockTest.java
  src/test/java/be/seeseemelk/mockbukkit/entity/EndermanMockTest.java
Labels: release/minor

#961 Permissions from plugin file
  extra/TestPlugin/src/main/resources/plugin.yml
  src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java
  src/main/java/be/seeseemelk/mockbukkit/PermissionManagerMock.java
  src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
  src/main/java/be/seeseemelk/mockbukkit/plugin/PluginManagerMock.java
  src/test/java/be/seeseemelk/mockbukkit/PermissionManagerMockTest.java
  src/test/resources/plugin.yml
Labels: release/minor
