Repository MockBukkit/MockBukkit, pull requests merged in 2025-03, with the labels that each got.

#1256 Inform the user about the `UnimplementedOperationException`
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
Labels: release/patch

#1305 Fix item meta mock equality defects
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMockTest.java
Labels: release/patch

#1307 Implemented logic for ShulkerBullet
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ShulkerBulletMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/ShulkerBulletMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1306 Implemented method death screen score in Player
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#1312 Added Entity Piglin and PiglinBrute
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PiglinAbstractMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PiglinBruteMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PiglinMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PiglinBruteMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PiglinMockTest.java
Labels: release/minor

#1313 Fix two player xp functions not throwing
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#1315 Added Entity Vex and Ominous Item Spawner
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/OminousItemSpawnerMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/VexMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/OminousItemSpawnerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/VexMockTest.java
Labels: release/minor

#1314 Added Entity Phantom and Lightning Strike
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/LightningStrikeMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PhantomMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/LightningStrikeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PhantomMockTest.java
Labels: release/minor

#1320 Added stubs for customName in Skulls
  src/main/java/org/mockbukkit/mockbukkit/block/state/SkullStateMock.java
Labels: release/patch

#1317 Start migration of ItemEntityMock to ItemMock
  src/main/java/org/mockbukkit/mockbukkit/entity/ItemEntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ItemMock.java
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/ItemMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/InventoryViewMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/patch

#1318 Added Entity Wandering Trader and Spawner Minecart
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/SpawnerMinecartMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/WanderingTraderMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/SpawnerMinecartMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/WanderingTraderMockTest.java
Labels: release/minor

#1323 Added stub methods
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryViewMock.java
  src/main/java/org/mockbukkit/mockbukkit/world/ChunkDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
Labels: release/patch

#1324 Added Entity Text Display
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/TextDisplayMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/TextDisplayMockTest.java
Labels: release/minor

#1325 Improved InventoryMock to mirror items properly
  src/main/java/org/mockbukkit/mockbukkit/block/BlockMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMirror.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/ChestStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMirrorTest.java
Labels: release/patch

#1326 fix(deps): Update junit
  build.gradle.kts
Labels: release/none

#1328 fix(deps): Updated JUnit to version 5.12.1 in MetaMiner
  metaminer/build.gradle.kts
Labels: release/none

#1309 Hide warnings in all workflows
  build.gradle.kts
Labels: release/none

#1329 Remove equals and hash code override in inventory mock + other fixes
  src/main/java/org/mockbukkit/mockbukkit/block/BlockMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/BlockStateMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/BrewingStandStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/ChestStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/FurnaceInventoryMockTest.java
Labels: release/patch

#1331 Implement more methods in HumanEntity and Projectile
  src/main/java/org/mockbukkit/mockbukkit/entity/AbstractProjectileMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/HumanEntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ProjectileMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/AbstractProjectileMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/HumanEntityMockTest.java
Labels: release/minor
