Repository MockBukkit/MockBukkit, pull requests merged in 2025-06, with the labels that each got.

#1377 Fix secrets not being passed to workflow call
  .github/workflows/publish.yml
  .github/workflows/tag.yml
Labels: release/none

#1374 Implement block data (Part 4)
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockFactory.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/CrafterDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/DoorDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/FenceGateDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/HopperDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/LecternDataMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/BlockTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockFactoryTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/CrafterDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/DoorDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/FenceGateDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/HopperDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/LecternDataMockTest.java
Labels: release/minor

#1384 Replace `UnimplementedOperationException` with null return
  src/main/java/org/mockbukkit/mockbukkit/entity/LivingEntityMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/LivingEntityMockTest.java
Labels: release/patch

#1379 Fix version prefix issue
  .github/workflows/tag.yml
Labels: release/none

#1385 1.21.6
  gradle.properties
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitInternalAPIBridge.java
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/BlockStateMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/sound/AudioExperience.java
  src/main/java/org/mockbukkit/mockbukkit/util/AdventureConverters.java
  src/main/resources-autogenerated/internal_tags/blocks/solid_blocks.json
  src/main/resources-autogenerated/keyed/attribute.json
  src/main/resources-autogenerated/keyed/block.json
  src/main/resources-autogenerated/keyed/cat_variant.json
  src/main/resources-autogenerated/keyed/entity_type.json
  src/main/resources-autogenerated/keyed/frog_variant.json
  src/main/resources-autogenerated/keyed/item.json
  src/main/resources-autogenerated/keyed/jukebox_song.json
  src/main/resources-autogenerated/keyed/map_decoration_type.json
  src/main/resources-autogenerated/keyed/mob_effect.json
  src/main/resources-autogenerated/keyed/sound_event.json
  src/main/resources-autogenerated/keyed/villager_profession.json
  src/main/resources-autogenerated/keyed/villager_type.json
  src/main/resources-autogenerated/materials/material_data.json
  src/main/resources-autogenerated/recipes/crafting.json
  src/main/resources-autogenerated/tags/blocks/happy_ghast_avoids.json
  src/main/resources-autogenerated/tags/blocks/triggers_ambient_desert_dry_vegetation_block_sounds.json
  src/main/resources-autogenerated/tags/blocks/triggers_ambient_desert_sand_block_sounds.json
  src/main/resources-autogenerated/tags/blocks/triggers_ambient_dried_ghast_block_sounds.json
  src/main/resources-autogenerated/tags/entity_types/can_equip_harness.json
  src/main/resources-autogenerated/tags/entity_types/dismounts_underwater.json
  src/main/resources-autogenerated/tags/entity_types/fall_damage_immune.json
  src/main/resources-autogenerated/tags/entity_types/followable_friendly_mobs.json
  src/main/resources-autogenerated/tags/items/happy_ghast_food.json
  src/main/resources-autogenerated/tags/items/happy_ghast_tempt_items.json
  src/main/resources-autogenerated/tags/items/harnesses.json
  src/main/resources-autogenerated/tags/items/horse_food.json
  src/main/resources-autogenerated/translations/en-us.json
  src/test/java/org/mockbukkit/mockbukkit/entity/variant/FrogVariantMockTest.java
  src/test/resources-autogenerated/itemstack/setType.json
Labels: release/minor

#1393 Add support for Happy Ghast
  src/main/java/org/mockbukkit/mockbukkit/entity/AnimalsMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/HappyGhastMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/HappyGhastMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/LivingEntityMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1392 Implement Brushable block data and block state
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/MaterialDataGenerator.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataLimitation.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockFactory.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BrushableDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/BlockStateMockFactory.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/BrushableBlockStateMock.java
  src/main/resources-autogenerated/materials/material_data.json
  src/test/java/org/mockbukkit/mockbukkit/block/BlockTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BrushableDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/BrushableBlockStateMockTest.java
  src/test/resources-autogenerated/blocks/block_states.csv
Labels: release/minor
