Repository MockBukkit/MockBukkit, pull requests merged in 2025-05, with the labels that each got.

#1356 Stub methods
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitInternalAPIBridge.java
  src/main/java/org/mockbukkit/mockbukkit/entity/AgeableMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ArmadilloMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/LivingEntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/OfflinePlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryViewMock.java
Labels: release/patch

#1359 Created stub for Potion Meta
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/PotionMetaMock.java
Labels: release/patch

#1358 Cleanup code smells
  src/main/java/org/mockbukkit/mockbukkit/entity/ArmorStandMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/BoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/TNTPrimedMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/WitherMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/scheduler/BukkitSchedulerMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/CrossbowMetaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/scheduler/BukkitSchedulerMockTest.java
Labels: release/patch

#1357 Implement setAffectsSpawning and setFlySpeed in PlayerMock
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#1355 Fix a multiple of dependency issues
  build.gradle.kts
Labels: release/patch

#1335 Implement block data (Part 2)
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/MaterialDataGenerator.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/AgeableDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/AmethystClusterDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/AnaloguePowerableBlockDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BarrelDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BedDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BisectedDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataLimitation.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockFactory.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockRegistry.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/CampfireDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/DecoratedPotDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/FenceDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/LevelledDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/SaplingDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/SnowableDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/StairsDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/SwitchDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/TrapDoorDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/WallSignDataMock.java
  src/main/resources/materials/material_data.json
  src/test/java/org/mockbukkit/mockbukkit/block/BlockTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/AgeableDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/AnaloguePowerableBlockDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BarrelDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/BisectedDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/SaplingDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/SnowableDataMockTest.java
Labels: release/minor

#1364 Implemented method SetVisualFire
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/EntityMockTest.java
Labels: release/patch

#1360 Add refresh dependency to checkstyle
  .github/workflows/linting.yaml
Labels: release/none

#1286 Added coverage badge
  README.md
Labels: release/none

#1316 Added example with MockBukkitExtension to README
  README.md
Labels: release/none

#1214 fix(workflow): update tag message to include commit ID and PR number
  .github/workflows/tag.yml
Labels: release/none

#1365 Implement block data (Part 3)
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataKey.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockFactory.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/ChestDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/EnderChestDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/LightDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/RailDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/RedstoneRailDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/RedstoneWallTorchDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/RedstoneWireDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/RepeaterDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/RotatableDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/TNTDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/WaterloggedDataMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/BlockTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/ChestDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/EnderChestDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/LightDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/RedstoneRailDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/RedstoneWallTorchDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/RedstoneWireDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/RepeaterDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/RotatableDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/TNTDataMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/data/WaterloggedDataMockTest.java
Labels: release/minor

#1206 Change coverage workflow name
  .github/workflows/coverage.yaml
Labels: release/none

#1368 Stub method
  metaminer/build.gradle.kts
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityMock.java
Labels: release/patch

#1106 Life cycle event manager implementation
  src/main/java/io/papermc/paper/plugin/lifecycle/event/types/LifecycleEventTypeProviderMock.java
  src/main/java/org/mockbukkit/mockbukkit/MockBukkit.java
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/CommandMapMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/CommandSourceStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/PluginVanillaCommandWrapperMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/VanillaCommandWrapperMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/WrappedLiteralCommandNode.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/AdventureMessageWrapper.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/ApiCommandMetaMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/BrigadierUtils.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/DummyCommandSender.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/MessageComponentSerializerMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/PaperCommandsMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitBrigadierForwardingMapMock.java
  src/main/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitCommandNode.java
  src/main/java/org/mockbukkit/mockbukkit/map/MapCanvasMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/PluginMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/LifecycleEventManagerMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/LifecycleEventRunnerMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/PaperLifecycleEventMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/TagEventTypeProviderMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/handler/configuration/AbstractLifecycleEventHandlerConfigurationMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/handler/configuration/MonitorLifecycleEventHandlerConfigurationMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/handler/configuration/PrioritizedLifecycleEventHandlerConfigurationMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/registrar/PaperRegistrarMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/registrar/RegistrarEventMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/types/AbstractLifecycleEventTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/types/MonitorableLifecycleEventTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/types/OwnerAwareLifecycleEventMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/types/PrioritizableLifecycleEventTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/util/UnsafeValuesMock.java
  src/main/resources/META-INF/services/io.papermc.paper.command.brigadier.MessageComponentSerializer
  src/main/resources/META-INF/services/io.papermc.paper.plugin.lifecycle.event.types.LifecycleEventTypeProvider
  src/test/java/io/papermc/paper/plugin/lifecycle/event/types/LifeCycleEventTypeProviderMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/BedStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/command/VanillaCommandWrapperMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/command/brigadier/PaperCommandsMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitBrigadierForwardingMapMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/enchantments/EnchantmentMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/DisplayMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/HopperInventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/plugin/PluginMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/plugin/lifecycle/event/MockLifecycleEventManagerTest.java
Labels: release/minor
