Repository MockBukkit/MockBukkit, pull requests merged in 2025-07, with the labels that each got.

#1395 Upgrade to PaperMC v1.21.7
  gradle.properties
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagsMock.java
  src/main/resources-autogenerated/keyed/item.json
  src/main/resources-autogenerated/keyed/jukebox_song.json
  src/main/resources-autogenerated/keyed/painting_variant.json
  src/main/resources-autogenerated/keyed/sound_event.json
  src/main/resources-autogenerated/tags/blocks/plays_ambient_desert_block_sounds.json
  src/main/resources-autogenerated/translations/en-us.json
  src/test/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitBrigadierForwardingMapMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/PlayerInventoryMockTest.java
  src/test/resources-autogenerated/itemstack/setType.json
Labels: release/minor

#1404 feat: Adding shaped recipes.
  src/main/java/org/mockbukkit/mockbukkit/inventory/RecipeManager.java
  src/test/java/org/mockbukkit/mockbukkit/command/brigadier/PaperCommandsMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/RecipeManagerTest.java
Labels: release/minor

#1408 feat: Adding particle spawning
  src/main/java/org/mockbukkit/mockbukkit/util/SpawnedParticle.java
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1412 feat: allow for more injections
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitInject.java
  src/test/java/org/mockbukkit/mockbukkit/MockBukkitExtensionDifferentMocksTest.java
Labels: release/minor

#1413 fix: Support Multiple Potion Effects of the Same Type
  src/main/java/org/mockbukkit/mockbukkit/entity/LivingEntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/potion/ActivePotionEffect.java
  src/test/java/org/mockbukkit/mockbukkit/potion/PotionEffectPriorityQueueTests.java
Labels: release/minor

#1416 chore: Cleanup ArmorStandMetaMock
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ArmorStandMetaMock.java
Labels: release/patch

#1420 feat: Enhance injection with broader Plugin support and entity types
  src/main/java/org/mockbukkit/mockbukkit/MockBukkit.java
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/MockBukkitConfiguredPluginClassLoader.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/PluginManagerMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/PluginMock.java
  src/test/java/org/mockbukkit/mockbukkit/MockBukkitExtensionDifferentMocksTest.java
  src/test/java/org/mockbukkit/mockbukkit/plugin/PluginManagerMockTest.java
Labels: release/minor

#1423 fix: hopefully final fixes for potion effects
  src/main/java/org/mockbukkit/mockbukkit/entity/LivingEntityMock.java
  src/test/java/org/mockbukkit/mockbukkit/potion/PotionEffectPriorityQueueTests.java
Labels: release/patch

#1422 Update com.vanniktech dependency
  build.gradle.kts
Labels: release/none

#1424 Fixed isSimilar method to look at item meta
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
Labels: release/patch
