Repository MockBukkit/MockBukkit, pull requests merged in 2025-01, with the labels that each got.

#1245 Implemented custom potion name in PotionMetaMock
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/PotionMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/meta/PotionMetaMockTest.java
Labels: release/minor

#1247 Improve MockBukkitInject to also support Server type.
  src/main/java/org/mockbukkit/mockbukkit/MockBukkitExtension.java
  src/test/java/org/mockbukkit/mockbukkit/MockBukkitExtensionTest.java
Labels: release/patch

#1248 Implement calling of PlayerLocaleChangeEvent
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#1246 Implemented Entities for all the Boat variants
  src/main/java/org/mockbukkit/mockbukkit/entity/BoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/ChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/AcaciaBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/AcaciaChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/BambooChestRaftMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/BambooRaftMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/BirchBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/BirchChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/CherryBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/CherryChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/DarkOakBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/DarkOakChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/JungleBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/JungleChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/MangroveBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/MangroveChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/OakBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/OakChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/PaleOakBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/PaleOakChestBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/SpruceBoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/boat/SpruceChestBoatMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/BoatMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1251 Implement sendActionBar
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
Labels: release/minor

#1250 Fix WorldMock#getGameRules method return data
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/patch

#1254 Fixes #1244 - [de]serializeItem to/from byte[] should include amount
  src/main/java/org/mockbukkit/mockbukkit/util/UnsafeValuesMock.java
  src/test/java/org/mockbukkit/mockbukkit/util/UnsafeValuesTest.java
Labels: release/patch

#1252 Implement Painting mocks
  src/main/java/org/mockbukkit/mockbukkit/art/ArtMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PaintingMock.java
  src/main/resources/keyed/painting_variant.json
  src/test/java/org/mockbukkit/mockbukkit/art/ArtMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PaintingMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1255 Moved left brackets to new line
  src/main/java/org/mockbukkit/mockbukkit/block/state/AbstractFurnaceStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/BoatMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/VillagerMock.java
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryMock.java
Labels: release/patch

#1200 Add Checkstyle workflow
  .github/workflows/linting.yaml
  build.gradle.kts
  config/checkstyle/checkstyle.xml
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/CrafterInventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/registry/RegistryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/none

#1253 Fix readme "Mock Plugins" example to show correct class PluginMock.
  README.md
Labels: release/none

#1257 Added MockBukkit version to BuildParameters
  build.gradle.kts
  src/main/java-templates/org/mockbukkit/mockbukkit/BuildParameters.java.peb
Labels: release/patch

#1259 Implemented entity Sniffer
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/SnifferMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/SnifferMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1069 Merge MetaMiner into the MockBukkit repository
  .gitignore
  build.gradle.kts
  metaminer/.gitignore
  metaminer/LICENSE
  metaminer/README.md
  metaminer/build.gradle.kts
  metaminer/gradle.properties
  metaminer/gradle/wrapper/gradle-wrapper.jar
  metaminer/gradle/wrapper/gradle-wrapper.properties
  metaminer/settings.gradle.kts
  metaminer/src/main/java/org/mockbukkit/metaminer/DataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/MetaMiner.java
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/MaterialDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/potion/PotionDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/tags/InternalTagDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/tags/InternalTagType.java
  metaminer/src/main/java/org/mockbukkit/metaminer/internal/tags/blocks/InternalBlockTagDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/KeyedClassTracker.java
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/KeyedDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/MethodDataScanner.java
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/RegistryKeyClassDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/tags/TagDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/tests/ItemMetaClassFinder.java
  metaminer/src/main/java/org/mockbukkit/metaminer/tests/ItemStackMetaDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/tests/ItemStackSetTypeTestDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/tests/ItemStackTestDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/translation/TranslationDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/util/JsonUtil.java
  metaminer/src/main/resources/plugin.yml
  settings.gradle.kts
Labels: release/none

#1267 Metaminer cleanup
  metaminer/build.gradle.kts
  metaminer/gradle.properties
  metaminer/gradle/wrapper/gradle-wrapper.jar
  metaminer/gradle/wrapper/gradle-wrapper.properties
  metaminer/settings.gradle.kts
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/MethodDataScanner.java
Labels: release/none

#1258 Implemented entities Creakings, Strider and Trader Llama
  src/main/java/org/mockbukkit/mockbukkit/entity/CreakingMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/EntityTypesMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/StriderMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/TraderLlamaMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/CreakingMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/StriderMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/TraderLlamaMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/world/WorldMockTest.java
Labels: release/minor

#1270 Fix class init issues related to typed keyed resources
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/KeyedDataGenerator.java
  metaminer/src/main/java/org/mockbukkit/metaminer/translation/TranslationDataGenerator.java
  src/main/java/org/mockbukkit/mockbukkit/block/BlockTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/datacomponent/DataComponentTypeMock.java
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryMock.java
  src/main/resources/keyed/data_component_type.json
  src/test/java/org/mockbukkit/mockbukkit/block/BlockTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/datacomponent/DataComponentTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/fluid/FluidMockTest.java
Labels: release/patch

#1272 Update resources with meta miner, and surfaced issues
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemFactoryMock.java
  src/main/resources/internal_tags/blocks/non_solid_blocks.json
  src/main/resources/internal_tags/blocks/solid_blocks.json
  src/main/resources/keyed/attribute.json
  src/main/resources/keyed/block.json
  src/main/resources/keyed/cat_variant.json
  src/main/resources/keyed/fluid.json
  src/main/resources/keyed/frog_variant.json
  src/main/resources/keyed/item.json
  src/main/resources/keyed/map_decoration_type.json
  src/main/resources/keyed/menu.json
  src/main/resources/keyed/mob_effect.json
  src/main/resources/keyed/potion.json
  src/main/resources/keyed/villager_profession.json
  src/main/resources/keyed/villager_type.json
  src/main/resources/keyed/worldgen/biome.json
  src/main/resources/keyed/worldgen/structure.json
  src/main/resources/materials/material_data.json
  src/test/java/org/mockbukkit/mockbukkit/entity/variant/CatVariantMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/variant/VillagerTypeMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/map/MapCursorTypeMockTest.java
  src/test/resources/itemstack/metaItemTypes.json
  src/test/resources/itemstack/setType.json
Labels: release/patch

#1271 Fix stackoverflow from unimplemented method in item stack
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemFactoryMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/meta/ItemMetaMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
Labels: release/patch

#1274 Improved MetaMiner method scanner
  metaminer/build.gradle.kts
  metaminer/src/main/java/org/mockbukkit/metaminer/json/AttributableElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/AttributeInstanceElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/AttributeModifierElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/CollectionElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/ColorElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/ComponentElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/ElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/EnumElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/EquipmentSlotGroupElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/KeyedElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/MapElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/PotionEffectElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/PrimitiveElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/keyed/MethodDataScanner.java
  metaminer/src/test/java/org/mockbukkit/metaminer/json/CollectionElementFactoryTest.java
  metaminer/src/test/java/org/mockbukkit/metaminer/json/ColorElementFactoryTest.java
  metaminer/src/test/java/org/mockbukkit/metaminer/json/EnumElementFactoryTest.java
  metaminer/src/test/java/org/mockbukkit/metaminer/json/KeyedElementFactoryTest.java
  metaminer/src/test/java/org/mockbukkit/metaminer/json/MapElementFactoryTest.java
  metaminer/src/test/java/org/mockbukkit/metaminer/json/PrimitiveElementFactoryTest.java
  metaminer/src/test/java/org/mockbukkit/metaminer/keyed/MethodDataScannerTest.java
Labels: release/none

#1275 Stubbed rayTrace method in WorldMock
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
  src/test/java/org/mockbukkit/mockbukkit/art/ArtMockTest.java
Labels: release/patch

#1276 Added support for Fluids, EntityTypes and GameEvents Tags
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/BaseTagMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/EntityTypeTagMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/FluidTagMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/GameEventTagMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/MaterialTagMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagFactory.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagParser.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagRegistry.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagWrapperMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagsMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/internal/InternalTagParser.java
  src/main/java/org/mockbukkit/mockbukkit/tags/internal/InternalTagRegistry.java
  src/main/resources/tags/blocks/tall_flowers.json
  src/main/resources/tags/items/flowers.json
  src/main/resources/tags/items/music_discs.json
  src/main/resources/tags/items/tall_flowers.json
  src/main/resources/tags/items/trim_templates.json
  src/test/java/org/mockbukkit/mockbukkit/ServerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/tags/RegistryTest.java
  src/test/java/org/mockbukkit/mockbukkit/tags/TagParserTest.java
  src/test/java/org/mockbukkit/mockbukkit/tags/TagRegistryTest.java
Labels: release/minor

#1278 InventoryMock getContents and getItem should return a clone
  src/main/java/org/mockbukkit/mockbukkit/inventory/InventoryMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/InventoryMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/PlayerInventoryMockTest.java
Labels: release/patch

#1279 Add basic implementation for exhaustion
  src/main/java/org/mockbukkit/mockbukkit/entity/HumanEntityMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/HumanEntityMockTest.java
Labels: release/minor

#1280 Fixed small typo in README.md
  README.md
Labels: release/none
