Repository MockBukkit/MockBukkit, pull requests merged in 2025-02, with the labels that each got.

#1282 Fix ItemStack not deserializing amount
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/ItemStackMockTest.java
Labels: release/patch

#1283 Add crafting recipes
  metaminer/src/main/java/org/mockbukkit/metaminer/MetaMiner.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/CollectionElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/ElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/ItemMetaElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/ItemStackElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/MapElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/BlastingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/CampfireRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/CookingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/CraftingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/RecipeChoiceElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/SmeltingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/SmithingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/SmokingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/json/recipe/StoneCuttingRecipeElementFactory.java
  metaminer/src/main/java/org/mockbukkit/metaminer/recipes/RecipeDataGenerator.java
  src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ComplexRecipeMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/CraftingRecipeFactory.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/ItemStackMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/RecipeManager.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/RecipeType.java
  src/main/resources/recipes/blasting.json
  src/main/resources/recipes/campfire_cooking.json
  src/main/resources/recipes/crafting.json
  src/main/resources/recipes/smelting.json
  src/main/resources/recipes/smithing.json
  src/main/resources/recipes/smoking.json
  src/main/resources/recipes/stonecutting.json
  src/test/java/org/mockbukkit/mockbukkit/ServerMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/CraftingRecipeFactoryTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/RecipeManagerTest.java
Labels: release/minor

#1287 Stub `getAttachedBlocks` in AbstractArrowMock
  src/main/java/org/mockbukkit/mockbukkit/entity/AbstractArrowMock.java
Labels: release/patch

#1285 Make url class loader be parrent of all classloaders
  src/main/java/org/mockbukkit/mockbukkit/plugin/CustomConfiguredPluginClassLoaderMock.java
  src/main/java/org/mockbukkit/mockbukkit/plugin/MockBukkitConfiguredPluginClassLoader.java
Labels: release/patch

#1288 Adding player-on-player damage and ability to retrieve the killer
  src/main/java/org/mockbukkit/mockbukkit/entity/LivingEntityMock.java
  src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
  src/main/java/org/mockbukkit/mockbukkit/simulate/entity/LivingEntitySimulation.java
  src/test/java/org/mockbukkit/mockbukkit/entity/LivingEntityMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/entity/PlayerMockTest.java
Labels: release/patch

#1291 Fixing jitpack command line
  jitpack.yml
Labels: release/none

#1295 Cleaning up loading of resources.
  src/main/java/org/mockbukkit/mockbukkit/adventure/Languages.java
  src/main/java/org/mockbukkit/mockbukkit/block/data/BlockDataMockRegistry.java
  src/main/java/org/mockbukkit/mockbukkit/food/FoodConsumption.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/RecipeManager.java
  src/main/java/org/mockbukkit/mockbukkit/potion/InternalPotionDataMock.java
  src/main/java/org/mockbukkit/mockbukkit/potion/PotionUtils.java
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryAccessMock.java
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryMock.java
  src/main/java/org/mockbukkit/mockbukkit/tags/TagFactory.java
  src/main/java/org/mockbukkit/mockbukkit/tags/internal/InternalTag.java
  src/main/java/org/mockbukkit/mockbukkit/tags/internal/InternalTagParser.java
  src/main/java/org/mockbukkit/mockbukkit/util/ResourceLoader.java
  src/test/java/org/mockbukkit/mockbukkit/util/ResourceLoaderTest.java
  src/test/resources/corrupted-resource.json
  src/test/resources/test-resource.json
Labels: release/patch

#1299 Fixed Chest Inventory State not being updated in test
  src/main/java/org/mockbukkit/mockbukkit/block/state/AbstractFurnaceStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/BeaconStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/block/state/LockableTileStateMock.java
  src/main/java/org/mockbukkit/mockbukkit/inventory/FurnaceInventoryMock.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/BeaconStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/ChestStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/block/state/ContainerStateMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/inventory/FurnaceInventoryMockTest.java
Labels: release/patch

#1302 Implemented new methods for CreakingMock and RegistryMock
  src/main/java/org/mockbukkit/mockbukkit/entity/CreakingMock.java
  src/main/java/org/mockbukkit/mockbukkit/registry/RegistryMock.java
  src/test/java/org/mockbukkit/mockbukkit/entity/CreakingMockTest.java
  src/test/java/org/mockbukkit/mockbukkit/registry/RegistryMockTest.java
Labels: release/minor
